Feature: Bulk Upload User from SA

  Scenario: Bulk upload users having limited applicatin access
    Given I am on the login page
    Then I log in as super user
    Then I should see Tile text User Admin
    And I click on the "Users" tile
    Then I should see header text "Users"
    Then I click on Import User button
    Then I click on Try Again button
    Then I enter user data
    Then I click on submit button on bulk user upload page
    Then I verify "19 users added" message

  Scenario Outline: and <Description>
    Given I am on mail login page
    Then I enter username "qaautomation@remedysystems.com" to login mail account
    Then I enter password "9h$00v3T$dF@OPn0" to login mail account
    Then I click on Mail icon in my account
    Then I click on Inbox in mail
    And I wait for 3000 milli seconds
    Then I verify account for user "<User>-<Role>"
    Then I set new password for the user "<User>-<Role>"

    Examples: 
      | Description                                           | User        | Role                            |
      | Verify email for Leader User                          | Super Admin | Leader                          |
      | Verify email for Manager User                         | Super Admin | Manager                         |
      | Verify email for Advanced Operator User               | Super Admin | Advanced Operator               |
      | Verify email for Physicians User                      | Super Admin | Physicians                      |
      | Verify email for Remedy TCS User                      | Super Admin | Remedy TCS                      |
      | Verify email for Remedy LPN User                      | Super Admin | Remedy LPN                      |
      | Verify email for Remedy RN User                       | Super Admin | Remedy RN                       |
      | Verify email for Remedy Field RN User                 | Super Admin | Remedy Field RN                 |
      | Verify email for Remedy PM User                       | Super Admin | Remedy PM                       |
      | Verify email for Remedy Sales Team User               | Super Admin | Remedy Sales Team               |
      | Verify email for Remedy Executive User                | Super Admin | Remedy Executive                |
      | Verify email for Prospective Partner Executive User   | Super Admin | Prospective Partner Executive   |
      | Verify email for Remedy Other User                    | Super Admin | Remedy Other                    |
      | Verify email for Partner Program Administrator User   | Super Admin | Partner Program Administrator   |
      | Verify email for Remedy Program Administrator User    | Super Admin | Remedy Program Administrator    |
      | Verify email for Partner Technical Administrator User | Super Admin | Partner Technical Administrator |
      | Verify email for Remedy Technical Administrator User  | Super Admin | Remedy Technical Administrator  |
      | Verify email for Operator User                        | Super Admin | Operator                        |
      | Verify email for Downstream Providers User            | Super Admin | Downstream Provider             |

  Scenario Outline: <Description>
    Given I am on the login page
    When I enter email field lbarinstein+qaadmin@remedypartners.com for login
    And I enter password field Testing1 for Login
    Then I click Access button
    Then I should see Tile text User Admin
    And I click on the "Users" tile
    Then I should see header text "Users"
    Then I search for bulk user with role "<User>-<Role>"
    Then I select user with role "<User>-<Role>"
    And I verify that I am navigated to user page
    Then I verify All Users button
    Then I click on All Users button
    Then I should see header text "Users"
    Then I search for bulk user with role "<User>-<Role>"
    Then I select user with role "<User>-<Role>"
    And I verify that I am navigated to user page
    Then I verify Edit Icon
    Then I click on Edit Icon
    Then I verify Delete User button
    Then I click on cross button on Edit User Page
    Then I verify Lock/Unlock Icon
    Then I verify first name "<FirstName>"
    Then I verify last name "<LastName>"
    Then I verify role "<Role>"
    Then I verify bulk email for "<User>-<Role>"
    Then I verify phone "<Phone>"
    Then I verify bulk NPI "<NPI>"
    Then I verify enabled "<ApplicationsEnabled>"
    Then I verify disabled "<ApplicationsDisabled>"
    Then I verify learning pathway "<LearningPathway>"
    Then I verify health system "<HealthSystem>"
    Then I verify programs "<Programs>"
    Then I verify location "<Locations>"

    Examples: 
      | Description                                                             | User        | UserName                               | Password | FirstName                                          | LastName                                           | Phone        | Role                            | ApplicationsEnabled                                                                                                 | ApplicationsDisabled                                                                               | NPI | LearningPathway                                                                                                                                                                                                              | HealthSystem                                                     | Programs                                                                                                   | Locations                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | View Leader user created from Super Admin user                          | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameeFirstNameeFirstNameeFirstNameeFirstName' | LastNameeeLastNameeeLastNameeeLastNameeeLastNamee' |              | Leader                          | Episode Connect, Episode Connect Classic, Remedy University, Care Innovation Institute                              | Reporting Classic, Reporting                                                                       |     | i am learning path, Learning Pathway 2, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University         | Hackensack, Blanchard Valley, WK Orthopedic Clinic               | Hackensack--BPCI Model 2, Blanchard Valley--BPCI Model 3, WK Orthopedic Clinic--BPCI Model 2               | Hackensack--2070-005--Hackensack University Medical Center, Blanchard Valley--3056-k60--Birchaven, Blanchard Valley--3056-k61--Independence House, WK Orthopedic Clinic--2070-a07--Aroostook Medical Center, WK Orthopedic Clinic--2070-a07--Fort Walton Beach Medical Center, WK Orthopedic Clinic--2070-a07--Highland Medical Center, WK Orthopedic Clinic--2070-a07--Kendall Medical Center, WK Orthopedic Clinic--2070-a07--Munroe Regional, WK Orthopedic Clinic--2070-a07--North Okaloosa Medical Center, WK Orthopedic Clinic--2070-a07--Uf Health Shands Hospital, WK Orthopedic Clinic--2070-a07--Willis Knighton Bossier Health Center, WK Orthopedic Clinic--2070-a07--Willis Knighton Medical Center, WK Orthopedic Clinic--2070-a07--Sacred Heart Hospital, WK Orthopedic Clinic--2070-a07--University health shreveport |
      | View Manager user created from Super Admin user                         | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | ManagerFirstName                                   | ManagerLastName                                    | 987-654-5678 | Manager                         | Episode Connect, Reporting Classic, Remedy University, Care Innovation Institute                                    | Episode Connect Classic, Reporting                                                                 |     |                                                                                                                                                                                                                              | Baptist Hospital Health System, Bridgeway, Nebraska Spine Center | Baptist Hospital Health System--BPCI Model 2, Bridgeway--BPCI Model 3, Nebraska Spine Center--BPCI Model 2 | Baptist Hospital Health System--2053-000--Mission Trails Baptist, Baptist Hospital Health System--2053-000--Northeast Baptist Hospital, Baptist Hospital Health System--2053-000--Baptist Medical Center, Bridgeway--3056-x52--Bridgeway Care And Rehab Center At Bridgewater, Nebraska Spine Center--2070-a12--Methodist Jennie Edmundson, Nebraska Spine Center--2070-a12--Nebraska Orthopaedic Hospital, Nebraska Spine Center--2070-a12--Bryan Medical Center, Nebraska Spine Center--2070-a12--The Nebraska Methodist Hospital                                                                                                                                                                                                                                                                                                   |
      | View Advanced Operator user created from Super Admin                    | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | AdvancedOperatorFirstName                          | AdvancedOperatorLastName                           | 987-980-0980 | Advanced Operator               | Episode Connect, Episode Connect Classic, Remedy University, Reporting, Care Innovation Institute                   | Reporting Classic                                                                                  |     |                                                                                                                                                                                                                              | Hackensack, Bridgeway                                            | Hackensack--BPCI Model 2, Bridgeway--BPCI Model 3                                                          | Hackensack--2070-005--Hackensack University Medical Center, Bridgeway--3056-x52--Bridgeway Care And Rehab Center At Bridgewater                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | View Physicians user created from Super Admin user                      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | PhysiciansFirstName                                | PhysiciansLastName                                 |              | Physicians                      | Episode Connect, Reporting Classic, Reporting, Care Innovation Institute                                            | Episode Connect Classic, Remedy University                                                         | NPI |                                                                                                                                                                                                                              | Hackensack, Baptist Hospital Health System                       | Hackensack--BPCI Model 2, Baptist Hospital Health System--BPCI Model 2                                     | Hackensack--2070-005--Hackensack University Medical Center, Baptist Hospital Health System--2053-000--Mission Trails Baptist, Baptist Hospital Health System--2053-000--Northeast Baptist Hospital, Baptist Hospital Health System--2053-000--Baptist Medical Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | View Remedy TCS user created from Super Admin user                      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | RTCSFirstName                                      | RTCSLastName                                       | 546-546-5655 | Remedy TCS                      | Episode Connect, Episode Connect for Post-acute Care, Community Connect, Care Connect, Care Innovation Institute    | Episode Connect Classic, Reporting Classic, Remedy University                                      |     |                                                                                                                                                                                                                              | Baptist Hospital Health System, Blanchard Valley                 | Baptist Hospital Health System--BPCI Model 2, Blanchard Valley--BPCI Model 3                               | Baptist Hospital Health System--2053-000--Mission Trails Baptist, Baptist Hospital Health System--2053-000--Northeast Baptist Hospital, Baptist Hospital Health System--2053-000--Baptist Medical Center, Blanchard Valley--3056-k60--Birchaven, Blanchard Valley--3056-k61--Independence House                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | View Remedy LPN user created from Super Admin user                      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | RLPNFirstName                                      | RLPNLastName                                       | 989-898-9898 | Remedy LPN                      | Episode Connect, Reporting Classic, Care Innovation Institute, Remedy University                                    | Episode Connect Classic, Episode Connect for Post-acute Care                                       |     |                                                                                                                                                                                                                              | Manitowoc Health & Rehab Center                                  | Manitowoc Health & Rehab Center--BPCI Model 3                                                              | Manitowoc Health & Rehab Center--3056-370--Manitowoc Health Care Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | View Remedy RN user created from Super Admin user                       | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | RRNFirstName                                       | RRNLastName                                        | 987-890-9878 | Remedy RN                       | Episode Connect, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Care Connect   | Episode Connect Classic, Episode Connect for Post-acute Care,                                      |     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University | TeamHealth                                                       | TeamHealth--BPCI Model 2, TeamHealth--BPCI Model 3                                                         | TeamHealth--2070-g15--Bethesda Hospital East, TeamHealth--2070-g15--Bethesda West Hospital, TeamHealth--2070-g15--Boca Raton Regional Hospital, TeamHealth--2070-g15--Delray Medical Center, TeamHealth--2070-g15--Good Samaritan Medical Center, TeamHealth--2070-g15--North Broward Medical Center, TeamHealth--2070-g15--West Boca Medical Center, TeamHealth--3056-q91--Rhea Medical Center, TeamHealth--3056-q91--The Medical Center At Franklin                                                                                                                                                                                                                                                                                                                                                                                 |
      | View Remedy Field RN user created from Super Admin user                 | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | RFRNFirstName                                      | RFRNFirstName                                      |              | Remedy Field RN                 | Episode Connect, Episode Connect Classic, Remedy University, Care Innovation Institute                              | Episode Connect for Post-acute Care, Reporting Classic                                             |     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External                                                                                                                       | Rothman                                                          | Rothman--BPCI Model 2                                                                                      | Rothman--2070-c80--Our Lady Of The Lake Regional Medical Center, Rothman--2070-c80--Baton Rouge General Medical Center, Rothman--2070-c80--The Spine Hospital of Louisiana, Rothman--2070-c80--Mary Hitchcock Memorial Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | View Remedy PM user created from Super Admin user                       | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | RPMFirstName                                       | RPMLastName                                        |              | Remedy PM                       | Episode Connect, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute                  | Episode Connect Classic, Remedy University                                                         |     |                                                                                                                                                                                                                              | WK Orthopedic Clinic                                             | WK Orthopedic Clinic--BPCI Model 2                                                                         | WK Orthopedic Clinic--2070-a07--Aroostook Medical Center, WK Orthopedic Clinic--2070-a07--Fort Walton Beach Medical Center, WK Orthopedic Clinic--2070-a07--Highland Medical Center, WK Orthopedic Clinic--2070-a07--Kendall Medical Center, WK Orthopedic Clinic--2070-a07--Munroe Regional, WK Orthopedic Clinic--2070-a07--North Okaloosa Medical Center, WK Orthopedic Clinic--2070-a07--Uf Health Shands Hospital, WK Orthopedic Clinic--2070-a07--Willis Knighton Bossier Health Center, WK Orthopedic Clinic--2070-a07--Willis Knighton Medical Center, WK Orthopedic Clinic--2070-a07--Sacred Heart Hospital, WK Orthopedic Clinic--2070-a07--University health shreveport                                                                                                                                                    |
      | View Remedy Sales Team user created from Super Admin user               | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | RSTFirstName                                       | RSTLastName                                        | 898-989-8787 | Remedy Sales Team               | Episode Connect, Care Innovation Institute, Remedy University                                                       | Reporting Classic                                                                                  |     |                                                                                                                                                                                                                              | Nebraska Spine Center                                            | Nebraska Spine Center--BPCI Model 2                                                                        | Nebraska Spine Center--2070-a12--Methodist Jennie Edmundson, Nebraska Spine Center--2070-a12--Nebraska Orthopaedic Hospital, Nebraska Spine Center--2070-a12--Bryan Medical Center, Nebraska Spine Center--2070-a12--The Nebraska Methodist Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | View Remedy Executive user created from Super Admin user                | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | REFirstName                                        | RELastName                                         |              | Remedy Executive                | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting, Care Innovation Institute | Reporting Classic, Remedy University, Community Connect                                            |     |                                                                                                                                                                                                                              | Jersey City Medical Center                                       | Jersey City Medical Center--BPCI Model 2                                                                   | Jersey City Medical Center--2070-007--Jersey City Medical Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | View Prospective Partner Executive user created from Super Admin user   | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | PPEFirstName                                       | PPELastName                                        |              | Prospective Partner Executive   | Episode Connect, Remedy University, Care Innovation Institute                                                       |                                                                                                    |     |                                                                                                                                                                                                                              | Branford Hills                                                   | Branford Hills--BPCI Model 3                                                                               | Branford Hills--3056-r29--Branford Hills Healthcare Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | View Remedy Other user created from Super Admin user                    | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | ROFirstName                                        | ROLastName                                         | 767-687-8998 | Remedy Other                    | Episode Connect, Community Connect, Care Connect, Reporting, Care Innovation Institute                              | Reporting Classic, Episode Connect Classic, Episode Connect for Post-acute Care, Remedy University |     |                                                                                                                                                                                                                              | Blanchard Valley                                                 | Blanchard Valley--BPCI Model 3                                                                             | Blanchard Valley--3056-k60--Birchaven, Blanchard Valley--3056-k61--Independence House                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | View Partner Program Administrator user created from Super Admin user   | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | PPAFirstName                                       | PPALastName                                        |              | Partner Program Administrator   | Episode Connect, Remedy University, Episode Connect for Post-acute Care, Care Innovation Institute                  | Episode Connect Classic, Reporting Classic                                                         |     |                                                                                                                                                                                                                              | Baptist Hospital Health System                                   | Baptist Hospital Health System--BPCI Model 2                                                               | Baptist Hospital Health System--2053-000--Mission Trails Baptist, Baptist Hospital Health System--2053-000--Northeast Baptist Hospital, Baptist Hospital Health System--2053-000--Baptist Medical Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | View Remedy Program Administrator user created from Super Admin user    | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | RPAFirstName                                       | RPALastName                                        | 987-776-6666 | Remedy Program Administrator    | Episode Connect, Reporting Classic, Care Innovation Institute, Reporting                                            | Episode Connect Classic, Episode Connect for Post-acute Care, Remedy University                    |     |                                                                                                                                                                                                                              | Bridgeway                                                        | Bridgeway--BPCI Model 3                                                                                    | Bridgeway--3056-x52--Bridgeway Care And Rehab Center At Bridgewater                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | View Partner Technical Administrator user created from Super Admin user | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | PTAFirstName                                       | PTALastName                                        |              | Partner Technical Administrator | Episode Connect, Administration, Remedy University, Reporting, Care Innovation Institute                            | Episode Connect Classic, Reporting Classic                                                         |     | Learning Pathway 2, New learning Path, Physician Acute Care Hospital Model 2, Remedy University                                                                                                                              | Hackensack                                                       | Hackensack--BPCI Model 2                                                                                   | Hackensack--2070-005--Hackensack University Medical Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | View Remedy Technical Administrator user created from Super Admin user  | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | RTAFirstName                                       | RTALastName                                        | 345-676-5432 | Remedy Technical Administrator  | Episode Connect, Reporting Classic, Administration, Care Innovation Institute                                       | Episode Connect Classic, Episode Connect for Post-acute Care, Remedy University                    |     |                                                                                                                                                                                                                              | Avalon                                                           | Avalon--BPCI Model 3                                                                                       | Avalon--3056-m78--Corvallis Manor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | View Operator user created from Super Admin user                        | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | OperatorFirstName                                  | OperatorLastName                                   |              | Operator                        | Episode Connect, Episode Connect Classic, Reporting Classic, Care Innovation Institute                              | Remedy University, Reporting                                                                       |     |                                                                                                                                                                                                                              | Sound Physicians                                                 | Sound Physicians--BPCI Model 2                                                                             | Sound Physicians--6005-080--Dodge County Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | View Downstream Provider user created from Super Admin user             | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | DPFirstName                                        | DPLastName                                         | 999-888-7770 | Downstream Provider             | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Care Innovation Institute            | Remedy University, Community Connect                                                               |     |                                                                                                                                                                                                                              | Healthsystem - Downstream Provider                               | Healthsystem - Downstream Provider--Downstream Organization                                                | Healthsystem - Downstream Provider--DOWN-ORG--Coosa Valley Health Care                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |

  Scenario Outline: <Description>
    Given I am on the login page
    Then I enter newuser email for "<User>-<Role>" login to Remedy
    Then I enter newuser password for login to Remedy
    And I click Access button
    Then I verify "<Applications>" product on SPOE page
    Then I verify "<ApplicationsNotVisible>" product is not visible on SPOE page
    #Then I click on Hamburger menu on top left of homepage
    #And I verify "<Applications>" in product menu dropdown
    #And I verify "<ApplicationsNotVisible>" is not present in product menu dropdown
    #And I redirect to Remedy connect page
    And I click on Episode1 tile for "<User>-<Role>" user
    #And I switch to new window
    And I verify "Dashboard" after redirection to EC1 for "<User>-<Role>" user
    And I click on username icon on right top corner "<User>-<Role>" and open user profile on EC1
    And I verify "<Facilities>" facility on user profile for "<User>-<Role>" user
    And I verify "Not Associated" payer on user profile for "<User>-<Role>" user
    And I verify "Medicare" payer on user profile for "<User>-<Role>" user
    And I should not see "Emblem" payer on user profile for "<User>-<Role>" user
    And I click on PatientList on SideMenu bar Episode1 for "<User>-<Role>" user
    And I verify Patient card appearing on Active Patients page for "<User>-<Role>" user
    And I click on gear menu and then click on Add Note and verify user role "<Roletext>" for "<User>-<Role>" user
    #And I switch back to old window
    #And I click on Institute tile for "<User>-<Role>" user
    #And I switch to new window
    #And I verify "<User>-<Role>" user navigated to Institute homepage
    #And I switch back to old window
    And I redirect to Remedy connect page
    And I click on Reports tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Reports homepage
    And I click on the Reports Tile with text "<ReportCategory>" for "<User>-<Role>" user
    Then I click on "<ReportName>" report text for Overall Program Reports for "<User>-<Role>" user
    Then I verify "<ReportName>" on the reports main page for "<User>-<Role>" user
    #When I click on field-panel-icon button for "<User>-<Role>" user
    #When I click to "BPID" field filter under "Episode Initiator" filter field for "<User>-<Role>" user
    #And I choose "Filter" option from select options of filter field for "<User>-<Role>" user
    #And I should see "<BPID>" in the filter value list for "<User>-<Role>" user
    #And I click on cancel button from filter for "<User>-<Role>" user
    And I redirect to Remedy connect page
    And I click on Episodes 2 tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Episodes 2 homepage
    And I verify patient card appearing on Episode 2 for "<User>-<Role>" user
    And I click on RemedyU tile for "<User>-<Role>" user
    And I switch to new window
    And I verify "<User>-<Role>" user navigated to RemedyU homepage
    And I verify details "<FirstName> <LastName>" for "<User>-<Role>" user on RemedyU dashboard
    And I verify learning pathway "<LearningPathway>" appearing for "<User>-<Role>" user on RemedyU dashboard
    And I switch back to old window
    And I redirect to Remedy connect page
    #And I click on Gainsharing Physician Survey tile for "<User>-<Role>" user
    #And I verify "<User>-<Role>" user navigated to Gainsharing Physician Survey homepage
    #And I redirect to Remedy connect page
    And I click on User Admin tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to User Admin homepage
    And I redirect to Remedy connect page
    And I click on the top user account link on remedy connect page
    And I verify "Support" in dropdown on profile icon for "<User>-<Role>" user
    And I verify "Reset Password" in dropdown on profile icon for "<Role>" user
    And I verify "Log Out" in dropdown on profile icon for "<Role>" user
    And I click on "Support" in dropdown on profile icon for "<User>-<Role>" user
    And I verify page header "Login" for "Support" on Remedy Connect for "<User>-<Role>" user
    Then I select Reset Password option from the dropdown
    And I should see text popup for reset password "We have sent you an e-mail with a link to reset your password."
    And I click Okay button for reset password popup
    Then I select Log Out option from the dropdown
    And I should see Log in widget

    Examples: 
      | Description                                                                                | User        | Email                                                    | FirstName                                          | LastName                                           | Role                            | Applications                                                                                                        | ApplicationsNotVisible                                                                                                           | Roletext       | ReportCategory | ReportName                   | BPID | LearningPathway                                                                                                                                                                                                              | Facilities                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | Login with Leader and verify Product Tiles and their redirections                          | Super Admin | qaautomation@remedysystems.com.executive@gmail.com       | FirstNameeFirstNameeFirstNameeFirstNameeFirstName' | LastNameeeLastNameeeLastNameeeLastNameeeLastNamee' | Leader                          | Episode Connect, Episode Connect Classic, Remedy University, Care Innovation Institute                              | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Reporting Classic, Reporting               | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      | i am learning path, Learning Pathway 2, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University         | Hackensack University Medical Center, Birchaven, Independence House, Aroostook Medical Center, B R F Hospital Holdings, Fort Walton Beach Medical Center, Highland Medical Center, Kendall Medical Center, Munroe Regional, North Okaloosa Medical Center, Uf Health Shands Hospital, Willis Knighton Bossier Health Center, Willis Knighton Medical Center, Aroostook Medical Center, B R F Hospital Holdings, Fort Walton Beach Medical Center, Highland Medical Center, Kendall Medical Center, Munroe Regional, North Okaloosa Medical Center, Uf Health Shands Hospital, Willis Knighton Bossier Health Center, Willis Knighton Medical Center |
      | Login with Manager and verify Product Tiles and their redirections                         | Super Admin | qaautomation@remedysystems.com.mgr@gmail.com             | ManagerFirstName                                   | ManagerLastName                                    | Manager                         | Episode Connect, Reporting Classic, Remedy University, Care Innovation Institute                                    | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Episode Connect Classic, Reporting         | ROLE_PRM       | Patient ID     | Episode DRG Issues [Model 3] |      |                                                                                                                                                                                                                              | Mission Trails Baptist, Northeast Baptist Hospital, Baptist Medical Center, Bridgeway Care And Rehab Center At Bridgewater, Methodist Jennie Edmundson, Nebraska Orthopaedic Hospital, Bryan Medical Center, The Nebraska Methodist Hospital, Alegent Health Mercy Hospital, Nebraska Spine Hospital                                                                                                                                                                                                                                                                                                                                                |
      | Login with Advanced Operator and verify Product Tiles and their redirections               | Super Admin | qaautomation@remedysystems.com.AdvanedOperator@gmail.com | AdvancedOperatorFirstName                          | AdvancedOperatorLastName                           | Advanced Operator               | Episode Connect, Episode Connect Classic, Remedy University, Reporting, Care Innovation Institute                   | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Reporting Classic                          | ROLE_TCS       | Patient ID     | Episode DRG Issues           |      |                                                                                                                                                                                                                              | Hackensack University Medical Center, Bridgeway Care And Rehab Center At Bridgewater                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | Login with Physicians and verify Product Tiles and their redirections                      | Super Admin | qaautomation@remedysystems.com.phys@gmail.com            | PhysiciansFirstName                                | PhysiciansLastName                                 | Physicians                      | Episode Connect, Reporting Classic, Reporting, Care Innovation Institute                                            | Episode Connect Classic, Remedy University, Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration | ROLE_CLINICIAN | Patient ID     | Episode DRG Issues           |      |                                                                                                                                                                                                                              | Hackensack University Medical Center, Mission Trails Baptist, Northeast Baptist Hospital, Baptist Medical Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | Login with Remedy TCS and verify Product Tiles and their redirections                      | Super Admin | qaautomation@remedysystems.com.rtcs@gmail.com            | RTCSFirstName                                      | RTCSLastName                                       | Remedy TCS                      | Episode Connect, Care Innovation Institute, Episode Connect for Post-acute Care, Community Connect, Care Connect    | Episode Connect Classic, Reporting Classic, Remedy University, Administration                                                    | ROLE_TCS       | Patient ID     | Episode DRG Issues           |      |                                                                                                                                                                                                                              | Mission Trails Baptist, Northeast Baptist Hospital, Baptist Medical Center, Birchaven, Independence House                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | Login with Remedy LPN and verify Product Tiles and their redirections                      | Super Admin | qaautomation@remedysystems.com.rlpn@gmail.com            | RLPNFirstName                                      | RLPNLastName                                       | Remedy LPN                      | Episode Connect, Reporting Classic, Care Innovation Institute, Remedy University                                    | Episode Connect Classic, Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration                    | ROLE_LPN       | Patient ID     | Episode DRG Issues [Model 3] |      |                                                                                                                                                                                                                              | Manitowoc Health Care Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | Login with Remedy RN and verify Product Tiles and their redirections                       | Super Admin | qaautomation@remedysystems.com.remedyrn@gmail.com        | RRNFirstName                                       | RRNLastName                                        | Remedy RN                       | Episode Connect, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Care Connect   | Episode Connect Classic, Episode Connect for Post-acute Care, Administration                                                     | ROLE_RN        | Patient ID     | Episode DRG Issues           |      | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University | Bethesda Hospital East, Bethesda West Hospital, Boca Raton Regional Hospital, Delray Medical Center, Good Samaritan Medical Center, North Broward Medical Center, West Boca Medical Center, Rhea Medical Center, The Medical Center At Franklin                                                                                                                                                                                                                                                                                                                                                                                                     |
      | Login with Remedy Field RN and verify Product Tiles and their redirections                 | Super Admin | qaautomation@remedysystems.com.remedyfrn@gmail.com       | RFRNFirstName                                      | RFRNLastName                                       | Remedy Field RN                 | Episode Connect, Episode Connect Classic, Care Innovation Institute, Remedy University                              | Episode Connect for Post-acute Care, Reporting Classic, Community Connect, Care Connect, Administration                          | ROLE_FRN       | Patient ID     | Episode DRG Issues           |      | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External                                                                                                                       | Our Lady Of The Lake Regional Medical Center, Baton Rouge General Medical Center, The Neuromedical Center Hospital, Mary Hitchcock Memorial Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | Login with Remedy PM and verify Product Tiles and their redirections                       | Super Admin | qaautomation@remedysystems.com.rpm@gmail.com             | RPMFirstName                                       | RPMLastName                                        | Remedy PM                       | Episode Connect, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute                  | Community Connect, Care Connect, Administration, Episode Connect Classic, Remedy University                                      | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      |                                                                                                                                                                                                                              | Aroostook Medical Center, B R F Hospital Holdings, Fort Walton Beach Medical Center, Highland Medical Center, Kendall Medical Center, Munroe Regional, North Okaloosa Medical Center, Uf Health Shands Hospital, Willis Knighton Bossier Health Center, Willis Knighton Medical Center, Munroe Regional, Uf Health Shands Hospital, North Okaloosa Medical Center, Kendall Medical Center                                                                                                                                                                                                                                                           |
      | Login with Remedy Sales Team and verify Product Tiles and their redirections               | Super Admin | qaautomation@remedysystems.com.remedyst@gmail.com        | RSTFirstName                                       | RSTLastName                                        | Remedy Sales Team               | Episode Connect, Care Innovation Institute, Remedy University                                                       | Reporting Classic, Episode Connect Classic, Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration |                | Patient ID     | Episode DRG Issues           |      |                                                                                                                                                                                                                              | Methodist Jennie Edmundson, Nebraska Orthopaedic Hospital, Bryan Medical Center, The Nebraska Methodist Hospital, Alegent Health Mercy Hospital, Nebraska Spine Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | Login with Remedy Executive and verify Product Tiles and their redirections                | Super Admin | qaautomation@remedysystems.com.remedye@gmail.com         | REFirstName                                        | RELastName                                         | Remedy Executive                | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting, Care Innovation Institute | Care Connect, Administration, Remedy University, Community Connect, Reporting Classic                                            | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      |                                                                                                                                                                                                                              | Jersey City Medical Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      #| Login with Prospective Partner Leader and verify Product Tiles and their redirections      | Super Admin | qaautomation@remedysystems.com.partnerpe@gmail.com       | PPEFirstName                                       | PPELastName                                        | Prospective Partner Executive   | Remedy University, Care Innovation Institute                                                               | Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Community Connect, Care Connect, Reporting, Administration |                | Patient ID     | Episode DRG Issues           |      |                                                                                                                                                                                                                              | Branford Hills Healthcare Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | Login with Remedy Other and verify Product Tiles and their redirections                    | Super Admin | qaautomation@remedysystems.com.remedyother@gmail.com     | ROFirstName                                        | ROLastName                                         | Remedy Other                    | Episode Connect, Care Innovation Institute, Community Connect, Care Connect, Reporting                              | Episode Connect Classic, Episode Connect for Post-acute Care, Remedy University, Reporting Classic, Administration               | ROLE_PRM       | Patient ID     | Episode DRG Issues [Model 3] |      |                                                                                                                                                                                                                              | Birchaven, Independence House                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | Login with Partner Program Administrator and verify Product Tiles and their redirections   | Super Admin | qaautomation@remedysystems.com.ppa@gmail.com             | PPAFirstName                                       | PPALastName                                        | Partner Program Administrator   | Episode Connect, Remedy University, Episode Connect for Post-acute Care, Care Innovation Institute                  | Episode Connect Classic, Reporting Classic, Community Connect, Care Connect, Reporting, Administration                           | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      |                                                                                                                                                                                                                              | Mission Trails Baptist, Northeast Baptist Hospital, Baptist Medical Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | Login with Remedy Program Administrator and verify Product Tiles and their redirections    | Super Admin | qaautomation@remedysystems.com.rpa@gmail.com             | RPAFirstName                                       | RPALastName                                        | Remedy Program Administrator    | Episode Connect, Reporting Classic, Care Innovation Institute, Reporting                                            | Episode Connect Classic, Episode Connect for Post-acute Care, Remedy University, Community Connect, Care Connect, Administration | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      |                                                                                                                                                                                                                              | Bridgeway Care And Rehab Center At Bridgewater                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | Login with Partner Technical Administrator and verify Product Tiles and their redirections | Super Admin | qaautomation@remedysystems.com.pta@gmail.com             | PTAFirstName                                       | PTALastName                                        | Partner Technical Administrator | Episode Connect, Administration, Remedy University, Reporting, Care Innovation Institute                            | Episode Connect Classic, Reporting Classic, Episode Connect for Post-acute Care, Community Connect, Care Connect                 | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      | Learning Pathway 2, New learning Path, Physician Acute Care Hospital Model 2, Remedy University                                                                                                                              | Hackensack University Medical Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | Login with Remedy Technical Administrator and verify Product Tiles and their redirections  | Super Admin | qaautomation@remedysystems.com.rta@gmail.com             | RTAFirstName                                       | RTALastName                                        | Remedy Technical Administrator  | Episode Connect, Reporting Classic, Administration, Care Innovation Institute                                       | Community Connect, Care Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Remedy University                 | ROLE_ADMIN     | Patient ID     | Episode DRG Issues [Model 3] |      |                                                                                                                                                                                                                              | Corvallis Manor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | Login with Operator and verify Product Tiles and their redirections                        | Super Admin | qaautomation@remedysystems.com.Operator@gmail.com        | OperatorFirstName                                  | OperatorLastName                                   | Operator                        | Episode Connect, Episode Connect Classic, Reporting Classic, Care Innovation Institute                              | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Remedy University, Reporting               | ROLE_TCS       | Patient ID     | Episode DRG Issues           |      | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Remedy University                                                                                                                                | Winchester Medical Center - Rehab Unit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | Login with Downstream Providers and verify Product Tiles and their redirections            | Super Admin | qaautomation@remedysystems.com.dp@gmail.com              | DPFirstName                                        | DPLastName                                         | Downstream Provider             | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Care Innovation Institute            | Administration, , Remedy University, Community Connect, Reporting Classic, Reporting, Care Connect                               | ROLE_SNF       | Patient ID     | Episode DRG Issues           |      |                                                                                                                                                                                                                              | Coosa valley health care                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
