Feature: Create user having partial application access- Super Admin User

  Scenario Outline: <Description>
    Given I am on the login page
    When I enter email field <UserName> for login
    And I enter password field <Password> for Login
    Then I click Access button
    Then I should see Tile text Users
    And I click on the "Users" tile
    Then I should see header text "Users"
    When I click on Add User button
    Then I should see "Add New User" on the user creation page
    Then I verify the header "General Information"
    And I fill in First Name with "<FirstName>"
    Then I fill in Last Name with <LastName>
    And I enter Email "<Email>" to Create user
    And I enter Phone field with <Phone>
    When I click the Organizational Role Field
    Then I pick a Organizational <Role>
    Then I enter NPI field with "<NPI>" for role "<Role>"
    Then I click on Next button
    Then I verify the header "Applications"
    Then I verify applications "<Applications>" are unchecked
    Then I verify Learning Pathway search box is not available
    Then I select "<Applications>" product
    Then I verify applications "<Applications>" are checked
    Then I click on Select button
    Then I verify Learning Pathway search box is available
    Then I select "<LearningPathwaySearchParameter>" from the results
    Then I verify "<ApplicationsNotVisible>" is not visible on Applications tab
    Then I click on Next button
    Then I verify the header "Permissions"
    And I search for health system with <Health System1>
    And I select a <Health System1>
    Then I select "<Programs1>" programs
    Then I select "<Locations1>" locations
    Then I click Add Organization button for "<HasHealthSystem2>" flag
    And I search for health system with <Health System2>
    And I select a <Health System2>
    Then I select "<Programs2>" programs
    Then I select "<Locations2>" locations
    Then I click Add Organization button for "<HasHealthSystem3>" flag
    And I search for health system with <Health System3>
    And I select a <Health System3>
    Then I select "<Programs3>" programs
    Then I select "<Locations3>" locations
    Then I click on Submit button for "<User>"
    And I click on the top user account link
    Then I click on "Log Out" button
    And I should see Log in widget
    Given I am on the login page
    Then I click on "Log Out" button again
    Given I am on mail login page
    Then I enter username "qaautomation@remedypartners.com" to login mail account
    Then I enter password "1Welcome2" to login mail account
    Then I click on Mail icon in my account
    Then I click on Inbox in mail
    And I wait for 3000 milli seconds
    Then I verify account for user "<User>-<Role>"
    Then I set new password for the user "<User>-<Role>"

    Examples: 
      | Description                                                                           | User        | UserName                               | Password | FirstName                                 | LastName                                 | Email                           | Phone      | Role                            | Applications                          | ApplicationsNotVisible                                                  | NPI | LearningPathwaySearchParameter                                                                                                                                                                                       | Health System1                  | Programs1                | Locations1                                                                                                                                                                                                                           | HasHealthSystem2 | Health System2                 | Programs2   | Locations2                                                                                               | HasHealthSystem3 | Health System3             | Programs3                | Locations3                                                                                                                                                                                                                           |
      | Login with Super Admin User and create user with Executive role                       | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstName      | LastNameLastNameLastNameLastNameLastName | qaautomation@remedypartners.com | 9988776655 | Executive                       | Episodes                              | Episodes 2.0, Administration, Physician Connect, TCI                    |     | i am learning path, Learning Pathway 2, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University | Sound Physicians                | BPCI-Model2              | 6005-080--Winchester Medical Center - Rehab Unit                                                                                                                                                                                     |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Manager role                         | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | lastnamelastnamelastnamelastnamelastname | qaautomation@remedypartners.com |            | Manager                         | Episodes, Reports                     | Episodes 2.0, Administration, Physician Connect, TCI                    |     | i am learning path, Learning Pathway 2, max-test-052417, 5HDc3E6aK_E1, p11D0Vl2FSg1, qfy2xp8zSFc1, 18h7phZr1h81, n9yn5n0Qa581                                                                                        | Avalon                          | BPCI-Model3              | 3056-m78--Corvallis Manor                                                                                                                                                                                                            |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Case Manager role                    | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstName      | LastName                                 | qaautomation@remedypartners.com |            | Case Manager                    | Episodes, Lessons                     | Episodes 2.0, Administration, Physician Connect, TCI                    |     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, qfy2xp8zSFc1, 18h7phZr1h81, n9yn5n0Qa581                    | Hackensack                      | BPCI-Model2              | 2070-005--Hackensack University Medical Center                                                                                                                                                                                       |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Physicians role                      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstName      | LastNameLastNameLastNameLastNameLastName | qaautomation@remedypartners.com | 9988776655 | Physicians                      | Episodes, Reports, Physician Connect  | Episodes 2.0, Administration, TCI                                       | NPI | i am learning path, 5HDc3E6aK_E1, p11D0Vl2FSg1, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University                                                                      | Bridgeway, Inc.                 | BPCI-Model3              | 3056-x52--Bridgeway Care And Rehab Center At Bridgewater                                                                                                                                                                             |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Remedy TCS role                      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedypartners.com |            | Remedy TCS                      | Episodes 2.0                          | Administration, Physician Connect                                       |     | Learning Pathway 2, jusUV22erpk1, 5HDc3E6aK_E1, Remedy University                                                                                                                                                    | Baptist Hospital Health System  | BPCI-Model2              | 2053-000--Mission Trails Baptist, 2053-000--Northeast Baptist Hospital, 2053-000--Baptist Medical Center                                                                                                                             |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Remedy LPN role                      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedypartners.com |            | Remedy LPN                      | Episodes, Episodes 2.0, Reports       | Administration, Physician Connect                                       |     |                                                                                                                                                                                                                      | Blanchard Valley                | BPCI-Model3              | 3056-k60--Birchaven, 3056-k61--Independence House                                                                                                                                                                                    |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Remedy RN role                       | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedypartners.com |            | Remedy RN                       | Episodes, Reports, TCI                | Administration, Physician Connect                                       |     | New learning Path, Learning Pathway 2, 3hSOHNAnvjc1, max-test-052417, p11D0Vl2FSg1, qfy2xp8zSFc1, 18h7phZr1h81, n9yn5n0Qa581                                                                                         | Branford Hills                  | BPCI-Model3              | All Locations                                                                                                                                                                                                                        |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Remedy Field RN role                 | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedypartners.com | 9988776655 | Remedy Field RN                 | Episodes, Reports, TCI                | Administration, Physician Connect                                       |     | HZhmTBQzHtU1, NFdw0Kts2C01, 3hSOHNAnvjc1, jusUV22erpk1, Care Coordination External                                                                                                                                   | Jersey City Medical Center      | BPCI-Model2              | All Locations                                                                                                                                                                                                                        |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Remedy PM role                       | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedypartners.com |            | Remedy PM                       | Reports, TCI                          | Administration, Physician Connect                                       |     | HZhmTBQzHtU1, NFdw0Kts2C01, p11D0Vl2FSg1, Executive Acute Care Hospital Model 2                                                                                                                                      | Nebraska Spine Center, LLP      | BPCI-Model2, BPCI-Model3 | 2070-a12--Methodist Jennie Edmundson, 2070-a12--Nebraska Orthopaedic Hospital, 2070-a12--Bryan Medical Center, 2070-a12--The Nebraska Methodist Hospital, 3056-a58--Alegent Health Mercy Hospital, 3056-a58--Nebraska Spine Hospital |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Remedy Sales Team role               | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName | qaautomation@remedypartners.com |            | Remedy Sales Team               | Reports                               | Episodes, Episodes 2.0, Administration, Physician Connect               |     | NFdw0Kts2C01, 3hSOHNAnvjc1, jusUV22erpk1, 5HDc3E6aK_E1, p11D0Vl2FSg1, qfy2xp8zSFc1, 18h7phZr1h81                                                                                                                     | WK Orthopedic Clinic            | BPCI-Model2, BPCI-Model3 | 2070-a07--All 2070-a07, 3056-a53--Munroe Regional, 3056-a53--Uf Health Shands Hospital, 3056-a53--North Okaloosa Medical Center, 3056-a53--Kendall Medical Center                                                                    |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Remedy Executive role                | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedypartners.com | 9988776655 | Remedy Executive                | Episodes 2.0                          | Administration, Physician Connect                                       |     | jusUV22erpk1, New learning Path, p11D0Vl2FSg1, qfy2xp8zSFc1                                                                                                                                                          | Rothman                         | BPCI-Model2, BPCI-Model3 | 2070-c80--Our Lady Of The Lake Regional Medical Center, 2070-c80--Baton Rouge General Medical Center, 2070-c80--The Neuromedical Center Hospital, 2070-c80--Mary Hitchcock Memorial Hospital, 3056-c86--All 3056-c86                 |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Prospective Partner Executive role   | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedypartners.com |            | Prospective Partner Executive   | Lessons                               | Administration, Physician Connect, Episodes, Episodes 2.0, Reports, TCI |     |                                                                                                                                                                                                                      | TeamHealth                      | BPCI-Model2, BPCI-Model3 | 2070-g15--All 2070-g15, 3056-q91--Rhea Medical Center, 3056-q91--The Medical Center At Franklin                                                                                                                                      |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Remedy Other role                    | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedypartners.com |            | Remedy Other                    | Episodes 2.0, TCI                     | Administration, Physician Connect, Reports                              |     | HZhmTBQzHtU1, n9yn5n0Qa581                                                                                                                                                                                           | Manitowoc Health & Rehab Center | BPCI-Model3              | 3056-370--Manitowoc Health Care Center                                                                                                                                                                                               |                  |                                |             |                                                                                                          |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Partner Program Administrator role   | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedypartners.com |            | Partner Program Administrator   | Episodes, Reports, Physician Connect  | Administration, TCI                                                     |     | NFdw0Kts2C01, 3hSOHNAnvjc1, jusUV22erpk1, Executive Acute Care Hospital Model 2                                                                                                                                      | Baptist Hospital Health System  | BPCI-Model2              | 2053-000--Mission Trails Baptist, 2053-000--Northeast Baptist Hospital, 2053-000--Baptist Medical Center                                                                                                                             | Yes              | Blanchard Valley               | BPCI-Model3 | 3056-k60--Birchaven, 3056-k61--Independence House                                                        |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Remedy Program Administrator role    | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedypartners.com |            | Remedy Program Administrator    | Episodes, Episodes 2.0, Reports,  TCI | Administration                                                          |     | Learning Pathway 2 , 3hSOHNAnvjc1, max-test-052417, 18h7phZr1h81                                                                                                                                                     | Hackensack                      | BPCI-Model2              | 2070-005--Hackensack University Medical Center                                                                                                                                                                                       | Yes              | Baptist Hospital Health System | BPCI-Model2 | 2053-000--Mission Trails Baptist, 2053-000--Northeast Baptist Hospital, 2053-000--Baptist Medical Center |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Partner Technical Administrator role | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedypartners.com | 9988776655 | Partner Technical Administrator | Episodes, Reports, Physician Connect  | Episodes 2.0, TCI                                                       |     | HZhmTBQzHtU1, Learning Pathway 2, Physician Acute Care Hospital Model 2, Remedy University                                                                                                                           | Hackensack                      | BPCI-Model2              | 2070-005--Hackensack University Medical Center                                                                                                                                                                                       | Yes              | Bridgeway, Inc.                | BPCI-Model3 | 3056-x52--Bridgeway Care And Rehab Center At Bridgewater                                                 |                  |                            |                          |                                                                                                                                                                                                                                      |
      | Login with Super Admin User and create user with Remedy Technical Administrator role  | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedypartners.com |            | Remedy Technical Administrator  | Physician Connect, Administration     |                                                                         |     | New learning Path , Learning Pathway 2, i am learning path , max-test-052417, qfy2xp8zSFc1, 18h7phZr1h81, n9yn5n0Qa581                                                                                               | Baptist Hospital Health System  | BPCI-Model2              | 2053-000--Mission Trails Baptist, 2053-000--Northeast Baptist Hospital, 2053-000--Baptist Medical Center                                                                                                                             | Yes              | Bridgeway, Inc.                | BPCI-Model3 | 3056-x52--Bridgeway Care And Rehab Center At Bridgewater                                                 | Yes              | Nebraska Spine Center, LLP | BPCI-Model2, BPCI-Model3 | 2070-a12--Methodist Jennie Edmundson, 2070-a12--Nebraska Orthopaedic Hospital, 2070-a12--Bryan Medical Center, 2070-a12--The Nebraska Methodist Hospital, 3056-a58--Alegent Health Mercy Hospital, 3056-a58--Nebraska Spine Hospital |
      | Login with Super Admin User and create user with Transitional Case Manager role       | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedypartners.com | 9988776655 | Transitional Case Manager       | Reports                               | Episodes 2.0,Administration, Physician Connect, TCI                     |     | HZhmTBQzHtU1, NFdw0Kts2C01, 3hSOHNAnvjc1, max-test-052417, n9yn5n0Qa581                                                                                                                                              | Hackensack                      | BPCI-Model2              | 2070-005--Hackensack University Medical Center                                                                                                                                                                                       | Yes              | Blanchard Valley               | BPCI-Model3 | 3056-k60--Birchaven, 3056-k61--Independence House                                                        | Yes              | WK Orthopedic Clinic       | BPCI-Model2, BPCI-Model3 | 2070-a07--All 2070-a07, 3056-a53--All 3056-a53                                                                                                                                                                                       |

  Scenario Outline: <Description>
    Given I am on the login page
    Then I enter newuser email for "<User>-<Role>" login to Remedy
    Then I enter newuser password for login to Remedy
    And I click Access button
    Then I verify "<Applications>" product on SPOE page
    Then I verify "<ApplicationsNotVisible>" product is not visible on SPOE page
    #Then I click on Hamburger menu on top left of homepage
    #And I verify "<Applications>" in product menu dropdown
    #And I verify "<ApplicationsNotVisible>" is not present in product menu dropdown
    #And I redirect to Remedy connect page
    And I click on Episode1 tile for "<User>-<Role>" user
    #And I switch to new window
    And I verify "Dashboard" after redirection to EC1 for "<User>-<Role>" user
    And I click on username icon on right top corner "<User>-<Role>" and open user profile on EC1
    And I verify "<Facilities>" facility on user profile for "<User>-<Role>" user
    And I verify "Not Associated" payer on user profile for "<User>-<Role>" user
    And I verify "Medicare" payer on user profile for "<User>-<Role>" user
    And I should not see "Emblem" payer on user profile for "<User>-<Role>" user
    And I click on PatientList on SideMenu bar Episode1 for "<User>-<Role>" user
    And I verify Patient card appearing on Active Patients page for "<User>-<Role>" user
    And I click on gear menu and then click on Add Note and verify user role "<Roletext>" for "<User>-<Role>" user
    #And I switch back to old window
    And I redirect to Remedy connect page
    And I click on Reports tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Reports homepage
    And I click on the Reports Tile with text "<ReportCategory>" for "<User>-<Role>" user
    Then I click on "<ReportName>" report text for Overall Program Reports for "<User>-<Role>" user
    Then I verify "<ReportName>" on the reports main page for "<User>-<Role>" user
    #When I click on field-panel-icon button for "<User>-<Role>" user
    #When I click to "BPID" field filter under "Episode Initiator" filter field for "<User>-<Role>" user
    #And I choose "Filter" option from select options of filter field for "<User>-<Role>" user
    #And I should see "<BPID>" in the filter value list for "<User>-<Role>" user
    #And I click on cancel button from filter for "<User>-<Role>" user
    And I redirect to Remedy connect page
    And I click on Episodes 2 tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Episodes 2 homepage
    And I verify patient card appearing on Episode 2 for "<User>-<Role>" user
    And I click on RemedyU tile for "<User>-<Role>" user
    And I switch to new window
    And I verify "<User>-<Role>" user navigated to RemedyU homepage
    And I verify details "<FirstName> <LastName>" for "<User>-<Role>" user on RemedyU dashboard
    And I verify learning pathway "<LearningPathway>" appearing for "<User>-<Role>" user on RemedyU dashboard
    And I switch back to old window
    And I redirect to Remedy connect page
    #And I click on Gainsharing Physician Survey tile for "<User>-<Role>" user
    #And I verify "<User>-<Role>" user navigated to Gainsharing Physician Survey homepage
    #And I redirect to Remedy connect page
    And I click on User Admin tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to User Admin homepage
    And I redirect to Remedy connect page
    #And I click on Institute tile for "<User>-<Role>" user
    #And I switch to new window
    #And I verify "<User>-<Role>" user navigated to Institute homepage
    #And I switch back to old window
    And I click on the top user account link on remedy connect page
    And I verify "Support" in dropdown on profile icon for "<User>-<Role>" user
    And I verify "Reset Password" in dropdown on profile icon for "<Role>" user
    And I verify "Log Out" in dropdown on profile icon for "<Role>" user
    And I click on "Support" in dropdown on profile icon for "<User>-<Role>" user
    And I verify page header "Login" for "Support" on Remedy Connect for "<User>-<Role>" user
    Then I select Reset Password option from the dropdown
    And I should see text popup for reset password "We have sent you an e-mail with a link to reset your password."
    And I click Okay button for reset password popup
    Then I select Log Out option from the dropdown
    And I should see Log in widget

    Examples: 
      | Description                                                                                | User        | FirstName                                 | LastName                                 | Role                            | Applications                         | ApplicationsNotVisible                                             | Roletext       | ReportCategory | ReportName                   | BPID | LearningPathway                                                                                                                                                                                                                                          | Facilities                                                                                                                                                                                                                                                                                                                                                             |
      | Login with Executive and verify Product Tiles and their redirections                       | Super Admin | FirstNameFirstNameFirstNameFirstName      | LastNameLastNameLastNameLastNameLastName | Executive                       | Episodes, TCI                        | Episodes 2.0, Reports, Lessons, Administration, Physician Connect  | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      | i am learning path, Learning Pathway 2, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University                                     | Winchester Medical Center - Rehab Unit                                                                                                                                                                                                                                                                                                                                 |
      | Login with Manager and verify Product Tiles and their redirections                         | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | Manager                         | Episodes, Reports, TCI               | Episodes 2.0, Administration, Physician Connect, Lessons           | ROLE_PRM       | Patient ID     | Episode DRG Issues [Model 3] |      |                                                                                                                                                                                                                                                          | Corvallis Manor                                                                                                                                                                                                                                                                                                                                                        |
      | Login with Case Manager and verify Product Tiles and their redirections                    | Super Admin | FirstNameFirstNameFirstNameFirstName      | LastName                                 | Case Manager                    | Episodes, TCI                        | Episodes 2.0, Administration, Physician Connect, Reports           | ROLE_TCS       | Patient ID     | Episode DRG Issues           |      | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University | Hackensack University Medical Center                                                                                                                                                                                                                                                                                                                                   |
      | Login with Physicians and verify Product Tiles and their redirections                      | Super Admin | FirstNameFirstNameFirstNameFirstName      | LastNameLastNameLastNameLastNameLastName | Physicians                      | Episodes, Reports, TCI               | Episodes 2.0, Administration, Lessons                              | ROLE_CLINICIAN | Patient ID     | Episode DRG Issues [Model 3] |      | i am learning path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University                                                         | Bridgeway Care and Rehab Center at Bridgewater                                                                                                                                                                                                                                                                                                                         |
      | Login with Remedy TCS and verify Product Tiles and their redirections                      | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | Remedy TCS                      | Episodes 2.0, TCI                    | Episodes, Administration, Physician Connect, Reports, Lessons      | ROLE_TCS       | Patient ID     | Episode DRG Issues           |      | Learning Pathway 2, max-test-052417, Care Coordination External, Remedy University                                                                                                                                                                       | Mission Trails Baptist, Northeast Baptist Hospital, Baptist Medical Center                                                                                                                                                                                                                                                                                             |
      | Login with Remedy LPN and verify Product Tiles and their redirections                      | Super Admin | FirstName                                 | LastName                                 | Remedy LPN                      | Episodes, Episodes 2.0, Reports, TCI | Administration, Physician Connect, Lessons                         | ROLE_LPN       | Patient ID     | Episode DRG Issues [Model 3] |      |                                                                                                                                                                                                                                                          | Birchaven, Independence House                                                                                                                                                                                                                                                                                                                                          |
      | Login with Remedy RN and verify Product Tiles and their redirections                       | Super Admin | FirstName                                 | LastName                                 | Remedy RN                       | Episodes, Reports, TCI               | Episodes 2.0, Administration, Physician Connect, Lessons           | ROLE_RN        | Patient ID     | Episode DRG Issues [Model 3] |      | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University                             | Branford Hills Healthcare Center                                                                                                                                                                                                                                                                                                                                       |
      | Login with Remedy Field RN and verify Product Tiles and their redirections                 | Super Admin | FirstName                                 | LastName                                 | Remedy Field RN                 | Episodes, Reports, TCI               | Episodes 2.0, Administration, Physician Connect, Lessons           | ROLE_FRN       | Patient ID     | Episode DRG Issues           |      | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External                                                                                                                                                   | Jersey City Medical Center                                                                                                                                                                                                                                                                                                                                             |
      | Login with Remedy PM and verify Product Tiles and their redirections                       | Super Admin | FirstName                                 | LastName                                 | Remedy PM                       | Reports, TCI                         | Episodes, Episodes 2.0, Administration, Physician Connect, Lessons | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      | Learning Pathway 2, New learning Path, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2                                                                                                                            | Methodist Jennie Edmundson, Nebraska Orthopaedic Hospital, Bryan Medical Center, The Nebraska Methodist Hospital, Alegent Health Mercy Hospital, Nebraska Spine Hospital                                                                                                                                                                                               |
      | Login with Remedy Sales Team and verify Product Tiles and their redirections               | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName | Remedy Sales Team               | Reports, TCI                         | Administration, Physician Connect, Episodes, Episodes 2.0, Lessons |                | Patient ID     | Episode DRG Issues           |      | i am learning path, Learning Pathway 2, max-test-052417, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2                                       | Munroe Regional, Uf Health Shands Hospital, North Okaloosa Medical Center, Kendall Medical Center, Fort Walton Beach Medical Center, Highland Medical Center - Christus, B R F Hospital Holdings, Willis Knighton Medical Center, Willis Knighton Bossier Health Center, Aroostook Medical Center                                                                      |
      | Login with Remedy Executive and verify Product Tiles and their redirections                | Super Admin | FirstName                                 | LastName                                 | Remedy Executive                | Episodes 2.0, TCI                    | Episodes, Administration, Physician Connect, Reports, Lessons      | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      | max-test-052417, New learning Path, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2                                                                                                                               | Our Lady Of The Lake Regional Medical Center, Baton Rouge General Medical Center, The Neuromedical Center Hospital, Mary Hitchcock Memorial Hospital, Cape Regional Medical Center Inc, Pottstown Memorial Medical Center, Hahnemann University Hospital, Christiana Care Hospital, Wilmington Hospital                                                                |
      #| Login with Prospective Partner Executive and verify Product Tiles and their redirections   | Super Admin | FirstName                                 | LastName                                 | Prospective Partner Executive   | Lessons, TCI                         | Administration, Physician Connect, Episodes, Episodes 2.0, Reports |                | Patient ID     | Episode DRG Issues           |      |                                                                                                                                                                                                                                                          | Bethesda Hospital East, North Broward Medical Center, Boca Raton Regional Hospital, Delray Medical Center, West Boca Medical Center, Good Samaritan Medical Center, Bethesda West Hospital, Rhea Medical Center, The Medical Center At Franklin                                                                                                                        |
      | Login with Remedy Other and verify Product Tiles and their redirections                    | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | Remedy Other                    | Episodes 2.0, TCI                    | Episodes, Administration, Physician Connect, Reports, Lessons      | ROLE_PRM       | Patient ID     | Episode DRG Issues [Model 3] |      | New learning Path, Remedy University                                                                                                                                                                                                                     | Manitowoc Health Care Center                                                                                                                                                                                                                                                                                                                                           |
      | Login with Partner Program Administrator and verify Product Tiles and their redirections   | Super Admin | FirstName                                 | LastName                                 | Partner Program Administrator   | Episodes, Reports, TCI               | Administration, Lessons                                            | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      | i am learning path, Learning Pathway 2, max-test-052417, Executive Acute Care Hospital Model 2                                                                                                                                                           | Mission Trails Baptist, Northeast Baptist Hospital, Baptist Medical Center, Birchaven, Independence House                                                                                                                                                                                                                                                              |
      | Login with Remedy Program Administrator and verify Product Tiles and their redirections    | Super Admin | FirstName                                 | LastName                                 | Remedy Program Administrator    | Episodes, Episodes 2.0, Reports, TCI | Physician Connect, Administration, Lessons                         | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      | i am learning path, Learning Pathway 2, max-test-052417, Physician Acute Care Hospital Model 2                                                                                                                                                           | Hackensack University Medical Center, Mission Trails Baptist, Northeast Baptist Hospital, Baptist Medical Center                                                                                                                                                                                                                                                       |
      | Login with Partner Technical Administrator and verify Product Tiles and their redirections | Super Admin | FirstName                                 | LastName                                 | Partner Technical Administrator | Episodes, Reports, TCI               | Episodes 2.0, Administration, Lessons                              | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      | Learning Pathway 2, New learning Path, Physician Acute Care Hospital Model 2, Remedy University                                                                                                                                                          | Hackensack University Medical Center, Bridgeway Care and Rehab Center at Bridgewater                                                                                                                                                                                                                                                                                   |
      | Login with Remedy Technical Administrator and verify Product Tiles and their redirections  | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | Remedy Technical Administrator  | Administration, TCI                  | Episodes, Episodes 2.0, Reports, Lessons                           | ROLE_ADMIN     | Patient ID     | Episode DRG Issues           |      | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University                                                                              | Mission Trails Baptist, Northeast Baptist Hospital, Baptist Medical Center, Bridgeway Care And Rehab Center At Bridgewater, Methodist Jennie Edmundson, Nebraska Orthopaedic Hospital, Bryan Medical Center, The Nebraska Methodist Hospital, Alegent Health Mercy Hospital, Nebraska Spine Hospital                                                                   |
      | Login with Transitional Case Manager and verify Product Tiles and their redirections       | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | Transitional Case Manager       | Reports, TCI                         | Episodes, Episodes 2.0, Administration, Physician Connect, Lessons | ROLE_TCS       | Patient ID     | Episode DRG Issues           |      | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Remedy University                                                                                                                                                            | Hackensack University Medical Center, Birchaven, Independence House, Munroe Regional, Uf Health Shands Hospital, North Okaloosa Medical Center, Kendall Medical Center, Fort Walton Beach Medical Center, Highland Medical Center - Christus, B R F Hospital Holdings, Willis Knighton Medical Center, Willis Knighton Bossier Health Center, Aroostook Medical Center |
