Feature: Create user having full application access- Super Admin User

  Scenario Outline: <Description>
    Given I am on the login page
    When I enter email field <UserName> for login
    And I enter password field <Password> for Login
    Then I click Access button
    Then I should see Tile text Users
    And I click on the "Users" tile
    Then I should see header text "Users"
    When I click on Add User button
    Then I should see "Add New User" on the user creation page
    Then I verify the header "General Information"
    And I fill in First Name with "<FirstName>"
    Then I fill in Last Name with <LastName>
    And I enter Email "<Email>" to Create user
    And I enter Phone field with <Phone>
    When I click the Organizational Role Field
    Then I verify role description "<RoleDescription>" for Role "<Role>"
    Then I pick a Organizational <Role>
    Then I enter NPI field with "<NPI>" for role "<Role>"
    Then I click on Next button
    Then I verify the header "Applications"
    Then I verify applications "<ApplicationsUnchecked>" are unchecked
    Then I verify Learning Pathway search box is not available
    Then I select "<Applications>" product
    Then I verify applications "<Applications>" are checked
    Then I click on Select button
    Then I verify Learning Pathway search box is available
    Then I select "<LearningPathwaySearchParameter>" from the results
    Then I verify "<ApplicationsNotVisible>" is not visible on Applications tab
    Then I click on Next button
    Then I verify the header "Permissions"
    And I search for health system with <Health System1>
    And I select a <Health System1>
    Then I select "<Programs1>" programs
    Then I select "<Locations1>" locations
    Then I click Add Organization button for "<HasHealthSystem2>" flag
    And I search for health system with <Health System2>
    And I select a <Health System2>
    Then I select "<Programs2>" programs
    Then I select "<Locations2>" locations
    Then I click Add Organization button for "<HasHealthSystem3>" flag
    And I search for health system with <Health System3>
    And I select a <Health System3>
    Then I select "<Programs3>" programs
    Then I select "<Locations3>" locations
    Then I click on Submit button for "<User>"
    And I click on the top user account link
    Then I click on "Log Out" button
    And I should see Log in widget
    Given I am on the login page
    Then I click on "Log Out" button again
    And I should see Log in widget
    Given I am on mail login page
    Then I enter username "qaautomation@remedysystems.com" to login mail account
    Then I enter password "9h$00v3T$dF@OPn0" to login mail account
    Then I click on Mail icon in my account
    Then I click on Inbox in mail
    And I wait for 3000 milli seconds
    Then I verify account for user "<User>-<Role>"
    Then I set new password for the user "<User>-<Role>"

    Examples: 
      | Description                                                                             | User        | UserName                               | Password | FirstName                                 | LastName                                 | Email                          | Phone      | Role                              | RoleDescription                                       | ApplicationsUnchecked                                                                                                                                              | Applications                                                                                                                                                                                                   | ApplicationsNotVisible                                                                                                                                          | NPI | LearningPathwaySearchParameter                                                                                                                                                                      | Health System1                                                         | Programs1                  | Locations1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | HasHealthSystem2 | Health System2    | Programs2    | Locations2                  | HasHealthSystem3 | Health System3                                                         | Programs3    | Locations3                              |
      #| Login with Super Admin User and create user with Leader role                            | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            | Leader                            | All Program, Financials and Physician-Level Reporting | Episode Connect Classic, Reporting Classic, Remedy University, Reporting                                                                                           | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                                                        |     | i am learning path, Learning Pathway 2, Remedy University                                                                                                                                           | Stamford Hospital                                                      | BPCI Model 2               | 2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Manager role                           | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            | Manager                           | Program Reporting Only                                | Episode Connect Classic, Reporting Classic, Remedy University, Reporting                                                                                           | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                                                        |     | i am learning path, Learning Pathway 2, max-test-052417, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2                                                               | Sound Physicians                                                       | BPCI Model 2, BPCI Model 3 | 6005-059--Presence Saint Joseph Medical Center, 6005-059--Evanston Hospital, 3090-068--Mountainview Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Advanced Operator role                 | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedysystems.com | 9988776655 | Advanced Operator                 | All Workflow and Operational Performance Reporting    | Episode Connect Classic, Reporting Classic, Remedy University, Reporting                                                                                           | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                                                        |     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, 5HDc3E6aK_E1                                                                                                            | St. Lukes Health Network, Inc. DBA St. Lukes University Health Network | BPCI Model 2               | 2070-025--Anderson                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Physicians role                        | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            | Physicians                        |                                                       | Episode Connect Classic, Reporting Classic, Remedy University, Reporting                                                                                           | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                                                        | NPI | i am learning path, 18h7phZr1h81, n9yn5n0Qa581                                                                                                                                                      | Trinity Health                                                         | BPCI Model 2               | 2070-c82--Saint Francis Hospital - Wilmington                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Remedy TCS role                        | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            | Remedy TCS                        |                                                       | Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Remedy University, Community Connect, Care Connect                                | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Care Connect                                | Administration, Program Management                                                                                                                              |     | Learning Pathway 2, jusUV22erpk1, Clinical Operations Acute Care Hospital Model 2, n9yn5n0Qa581, 18h7phZr1h81                                                                                       | Stamford Hospital                                                      | BPCI Model 2               | 2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Remedy LPN role                        | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            | Remedy LPN                        |                                                       | Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Remedy University                                                                 | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University                                                                 | Community Connect, Care Connect, Administration, Program Management                                                                                             |     |                                                                                                                                                                                                     | Stamford Hospital                                                      | BPCI Model 2               | 2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Remedy RN role                         | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedysystems.com | 9988776655 | Remedy RN                         |                                                       | Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Remedy University, Community Connect, Care Connect                                | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Care Connect                                | Administration, Program Management                                                                                                                              |     | New learning Path, Learning Pathway 2, 3hSOHNAnvjc1, max-test-052417, 5HDc3E6aK_E1, p11D0Vl2FSg1, qfy2xp8zSFc1, 18h7phZr1h81, n9yn5n0Qa581                                                          | Stamford Hospital                                                      | BPCI Model 2               | 2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Remedy Field RN role                   | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedysystems.com |            | Remedy Field RN                   |                                                       | Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Remedy University                                                                 | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University                                                                 | Community Connect, Care Connect, Administration, Program Management                                                                                             |     | HZhmTBQzHtU1, NFdw0Kts2C01, 3hSOHNAnvjc1, jusUV22erpk1, 5HDc3E6aK_E1, p11D0Vl2FSg1, qfy2xp8zSFc1, 18h7phZr1h81                                                                                      | Stamford Hospital                                                      | BPCI Model 2               | 2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Remedy PM role                         | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            | Remedy PM                         |                                                       | Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Remedy University                                                                 | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University                                                                 | Community Connect, Care Connect, Administration, Program Management                                                                                             |     | HZhmTBQzHtU1, NFdw0Kts2C01, p11D0Vl2FSg1, qfy2xp8zSFc1                                                                                                                                              | Stamford Hospital                                                      | BPCI Model 2               | 2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Remedy Sales Team role                 | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            | Remedy Sales Team                 |                                                       | Reporting Classic, Remedy University                                                                                                                               | Episode Connect, Reporting Classic, Care Innovation Institute, Remedy University                                                                                                                               | Episode Connect Classic, Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                               |     | NFdw0Kts2C01, 3hSOHNAnvjc1, jusUV22erpk1, Clinical Operations Acute Care Hospital Model 2                                                                                                           | Stamford Hospital                                                      | BPCI Model 2               | 2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Remedy Executive role                  | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedysystems.com | 9988776655 | Remedy Executive                  |                                                       | Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Remedy University, Community Connect, Reporting, Program Management               | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Reporting, Program Management               | Care Connect, Administration                                                                                                                                    |     | jusUV22erpk1, New learning Path, n9yn5n0Qa581                                                                                                                                                       | Sound Physicians                                                       | BPCI Model 3               | 3090-068--Mountainview Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | Yes              | Stamford Hospital | BPCI Model 2 | 2070-015--Stamford Hospital | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Prospective Partner Executive role     | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            | Prospective Partner Executive     |                                                       | Remedy University                                                                                                                                                  | Remedy University, Care Innovation Institute                                                                                                                                                                   | Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Community Connect, Care Connect, Reporting, Administration, Program Management |     |                                                                                                                                                                                                     | Sound Physicians                                                       | BPCI Model 2               | 6005-059--Presence Saint Joseph Medical Center, 6005-059--Evanston Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | No               |                   |              |                             | No               |                                                                        |              |                                         |
      | Login with Super Admin User and create user with Remedy Other role                      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            | Remedy Other                      |                                                       | Episode Connect Classic, Episode Connect for Post-acute Care, Remedy University, Reporting Classic, Community Connect, Care Connect, Reporting, Program Management | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Care Innovation Institute, Remedy University, Reporting Classic, Community Connect, Care Connect, Reporting, Program Management | Administration                                                                                                                                                  |     | HZhmTBQzHtU1, 18h7phZr1h81                                                                                                                                                                          | Stamford Hospital                                                      | BPCI Model 2               | All Locations                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Partner Program Administrator role     | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedysystems.com |            | Partner Program Administrator     |                                                       | Episode Connect Classic, Reporting Classic, Remedy University, Episode Connect for Post-acute Care                                                                 | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Care Innovation Institute, Episode Connect for Post-acute Care                                                                 | Community Connect, Care Connect, Reporting, Administration, Program Management                                                                                  |     | NFdw0Kts2C01, 3hSOHNAnvjc1, jusUV22erpk1, Physician Acute Care Hospital Model 2, Remedy University                                                                                                  | Stamford Hospital                                                      | BPCI Model 2               | 2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Remedy Program Administrator role      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedysystems.com | 9988776655 | Remedy Program Administrator      |                                                       | Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Remedy University, Reporting                                                      | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Reporting                                                      | Community Connect, Care Connect, Administration, Program Management                                                                                             |     | Learning Pathway 2 , 3hSOHNAnvjc1, max-test-052417, qfy2xp8zSFc1, 18h7phZr1h81, n9yn5n0Qa581                                                                                                        | Trinity Health                                                         | BPCI Model 2               | 2070-c82--Saint Francis Hospital, 2070-c90--Albany Memorial Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Yes              | Stamford Hospital | BPCI Model 2 | 2070-015--Stamford Hospital | Yes              | St. Lukes Health Network, Inc. DBA St. Lukes University Health Network | BPCI Model 2 | 2070-025--Anderson, 2070-023--Bethlehem |
      #| Login with Super Admin User and create user with Partner Technical Administrator role   | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            | Partner Technical Administrator   |                                                       | Episode Connect Classic, Reporting Classic, Administration, Remedy University, Reporting                                                                           | Episode Connect, Episode Connect Classic, Reporting Classic, Administration, Remedy University, Reporting, Care Innovation Institute                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Program Management                                                                        |     | HZhmTBQzHtU1, Learning Pathway 2, n9yn5n0Qa581                                                                                                                                                      | Sound Physicians                                                       | BPCI Model 2, BPCI Model 3 | 6005-059--Presence Saint Joseph Medical Center, 3090-068--Mountainview Hospital, 3090-191--Mountainview Hospital, 3090-068--Vaughan Regional Medical Center Parkway Campus, 3090-068--San Mateo Medical Center, 3090-068--Aroostook Medical Center, 3090-068--Mayo Clinic Health System - Mankato, 3090-068--St Vincent Healthcare, 3090-068--St Rose Dominican Hospitals - Rose De Lima Campus, 3090-068--Valley Hospital Medical Center, 3090-068--Desert Springs Hosp MC, 3090-068--Summerlin Hospital Medical Center, 3090-068--St Rose Dominican Hospitals - Siena Campus, 3090-068--Spring Valley Hospital Medical Center | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Remedy Technical Administrator role    | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedysystems.com | 9988776655 | Remedy Technical Administrator    |                                                       | Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Administration, Remedy University                                                 | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Administration, Care Innovation Institute, Remedy University                                                 | Community Connect, Care Connect, Program Management                                                                                                             |     | New learning Path , Learning Pathway 2, i am learning path , max-test-052417, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, qfy2xp8zSFc1, 18h7phZr1h81, n9yn5n0Qa581 | Stamford Hospital                                                      | BPCI Model 2               | 2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Operator role                          | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            | Operator                          | Workflow Reporting Only                               | Episode Connect Classic, Reporting Classic, Remedy University, Reporting                                                                                           | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                                                        |     | HZhmTBQzHtU1, NFdw0Kts2C01, 3hSOHNAnvjc1, max-test-052417, 5HDc3E6aK_E1, p11D0Vl2FSg1, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University              | St. Lukes Health Network, Inc. DBA St. Lukes University Health Network | BPCI Model 2               | All Locations                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Remedy Sales Acute Demo 2018 role      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            | Remedy Sales Acute Demo 2018      |                                                       | Episode Connect Classic, Reporting Classic, Remedy University, Episode Connect for Post-acute Care                                                                 | Episode Connect, Care Innovation Institute, Episode Connect Classic, Reporting Classic, Remedy University, Episode Connect for Post-acute Care                                                                 | Community Connect, Care Connect, Administration, Program Management, Reporting                                                                                  |     | Physician Acute Care Hospital Model 2, Remedy University                                                                                                                                            | St. Lukes Health Network, Inc. DBA St. Lukes University Health Network | BPCI Model 2               | 2070-025--Anderson                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Remedy Sales PAC Demo 2018 role        | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            | Remedy Sales PAC Demo 2018        |                                                       | Episode Connect Classic, Episode Connect for Post-acute Care                                                                                                       | Episode Connect, Care Innovation Institute, Episode Connect Classic, Episode Connect for Post-acute Care                                                                                                       | Community Connect, Care Connect, Administration, Program Management, Reporting, Reporting Classic, Remedy University                                            |     | Physician Acute Care Hospital Model 2, Remedy University                                                                                                                                            | St. Lukes Health Network, Inc. DBA St. Lukes University Health Network | BPCI Model 2               | 2070-025--Anderson, 2070-023--Bethlehem                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | No               |                   |              |                             | No               |                                                                        |              |                                         |
      #| Login with Super Admin User and create user with Remedy Sales Commercial Demo 2018 role | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            | Remedy Sales Commercial Demo 2018 |                                                       | Episode Connect for Post-acute Care                                                                                                                                | Episode Connect, Care Innovation Institute, Episode Connect for Post-acute Care                                                                                                                                | Community Connect, Care Connect, Administration, Program Management, Reporting, Reporting Classic, Remedy University, Episode Connect Classic                   |     |                                                                                                                                                                                                     | St. Lukes Health Network, Inc. DBA St. Lukes University Health Network | BPCI Model 2               | 2070-025--Anderson, 2070-023--Bethlehem                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | No               |                   |              |                             | No               |                                                                        |              |                                         |

  Scenario Outline: <Description>
    Given I am on the login page
    Then I enter newuser email for "<User>-<Role>" login to Remedy
    Then I enter newuser password for login to Remedy
    And I click Access button
    Then I verify "<Applications>" product on SPOE page
    Then I verify "<ApplicationsNotVisible>" product is not visible on SPOE page
    #######Episode Connect Classic Provisioning################
    And I click on Episode1 tile for "<User>-<Role>" user
    And I verify "Dashboard" after redirection to EC1 for "<User>-<Role>" user
    And I click on username icon on right top corner "<User>-<Role>" and open user profile on EC1
    And I verify "<Facilities>" facility on user profile for "<User>-<Role>" user
    And I verify "Not Associated" payer on user profile for "<User>-<Role>" user
    And I verify "Medicare" payer on user profile for "<User>-<Role>" user
    And I should not see "Emblem" payer on user profile for "<User>-<Role>" user
    And I click on PatientList on SideMenu bar Episode1 for "<User>-<Role>" user
    And I verify Patient card appearing on Active Patients page for "<User>-<Role>" user
    And I click on gear menu and then click on Add Note and verify user role "<Roletext>" for "<User>-<Role>" user
    And I redirect to Remedy connect page
    ###########Reporting Classic Provisioning##############
    And I click on Reports tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Reports homepage
    And I click on the Reports Tile with text "<ReportCategory>" for "<User>-<Role>" user
    Then I click on "<ReportName>" report text for Overall Program Reports for "<User>-<Role>" user
    Then I verify "<ReportName>" on the reports main page for "<User>-<Role>" user
    And I redirect to Remedy connect page
    ###########Episode Connect Post Acute Care Provisioning##############
    And I click on Episodes 2 tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Episodes 2 homepage
    And I verify patient card appearing on Episode 2 for "<User>-<Role>" user
    And I redirect to Remedy connect page
    ############Remedy University Provisioning###############
    And I click on RemedyU tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to RemedyU homepage
    And I verify details "<FirstName> <LastName>" for "<User>-<Role>" user on RemedyU dashboard
    And I verify learning pathway "<LearningPathway>" appearing for "<User>-<Role>" user on RemedyU dashboard
    And I redirect to Remedy connect page
    ############User Admin Provisioning###################################
    And I click on User Admin tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to User Admin homepage
    And I redirect to Remedy connect page
    #############TCI Provisioning####################################
    #And I click on Institute tile for "<User>-<Role>" user
    #And I verify "<User>-<Role>" user navigated to Institute homepage
    #And I redirect to Remedy connect page
    #################Program Management Tile Provisioning####################
    And I click on Program Management tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Program Management homepage
    And I redirect to Remedy connect page
    #################Care Connect Tile Provisioning####################
    And I click on Care Connect tile for  "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Care Connect homepage
    And I redirect to Remedy connect page
    #################Community Connect Tile Provisioning####################
    And I click on Community Connect tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Community Connect homepage
    And I redirect to Remedy connect page
    ###############Reporting Provisioning###################################
    And I click on Reporting tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Reporting homepage
    And I redirect to Remedy connect page
    #################General Verification################################
    And I click on the top user account link on remedy connect page
    And I verify "Support" in dropdown on profile icon for "<User>-<Role>" user
    And I verify "Reset Password" in dropdown on profile icon for "<Role>" user
    And I verify "Log Out" in dropdown on profile icon for "<Role>" user
    And I click on "Support" in dropdown on profile icon for "<User>-<Role>" user
    And I verify page header "Login" for "Support" on Remedy Connect for "<User>-<Role>" user
    Then I select Reset Password option from the dropdown
    And I should see text popup for reset password "We have sent you an e-mail with a link to reset your password."
    And I click Okay button for reset password popup
    Then I select Log Out option from the dropdown
    And I should see Log in widget

    Examples: 
      | Description                                                                                  | User        | FirstName                                 | LastName                                 | Role                              | Applications                                                                                                                                                                                                   | ApplicationsNotVisible                                                                                                                        | Roletext       | ReportCategory | ReportName         | BPID | Facilities                                                                                                                                                                                                                                                                                                                                                                            | LearningPathway                                                                                                                                                                                                                                          |
      #| Login with Leader and verify Product Tiles and their redirections                            | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName | Leader                            | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                                      | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | i am learning path, Learning Pathway 2, Remedy University                                                                                                                                                                                                |
      #| Login with Manager and verify Product Tiles and their redirections                           | Super Admin | FirstName                                 | LastName                                 | Manager                           | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                                      | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Presence Saint Joseph Medical Center, Evanston Hospital, Mountainview Hospital                                                                                                                                                                                                                                                                                                        | i am learning path, Learning Pathway 2, max-test-052417, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2                                                                                                                    |
      #| Login with Advanced Operator and verify Product Tiles and their redirections                 | Super Admin | FirstName                                 | LastName                                 | Advanced Operator                 | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                                      | ROLE_TCS       | Patient ID     | Episode DRG Issues |      | Anderson                                                                                                                                                                                                                                                                                                                                                                              | i am learning path, Learning Pathway 2, max-test-052417, Care Coordination External                                                                                                                                                                      |
      #| Login with Physicians and verify Product Tiles and their redirections                        | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName | Physicians                        | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                                      | ROLE_CLINICIAN | Patient ID     | Episode DRG Issues |      | Saint Francis Hospital - Wilmington                                                                                                                                                                                                                                                                                                                                                   | i am learning path, Physician Acute Care Hospital Model 2, Remedy University                                                                                                                                                                             |
      #| Login with Remedy TCS and verify Product Tiles and their redirections                        | Super Admin | FirstName                                 | LastName                                 | Remedy TCS                        | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Care Connect                                | Administration, Program Management                                                                                                            | ROLE_TCS       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | Learning Pathway 2, max-test-052417, Clinical Operations Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University                                                                                                           |
      #| Login with Remedy LPN and verify Product Tiles and their redirections                        | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | Remedy LPN                        | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University                                                                 | Community Connect, Care Connect, Administration, Program Management                                                                           | ROLE_LPN       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                          |
      #| Login with Remedy RN and verify Product Tiles and their redirections                         | Super Admin | FirstName                                 | LastName                                 | Remedy RN                         | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Care Connect                                | Administration, Program Management                                                                                                            | ROLE_RN        | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University |
      #| Login with Remedy Field RN and verify Product Tiles and their redirections                   | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | Remedy Field RN                   | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University                                                                 | Community Connect, Care Connect, Administration, Program Management                                                                           | ROLE_FRN       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2                    |
      #| Login with Remedy PM and verify Product Tiles and their redirections                         | Super Admin | FirstName                                 | LastName                                 | Remedy PM                         | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University                                                                 | Community Connect, Care Connect, Administration, Program Management                                                                           | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | Learning Pathway 2, New learning Path, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2                                                                                                                            |
      #| Login with Remedy Sales Team and verify Product Tiles and their redirections                 | Super Admin | FirstName                                 | LastName                                 | Remedy Sales Team                 | Episode Connect, Reporting Classic, Care Innovation Institute, Remedy University                                                                                                                               | Episode Connect Classic, Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management             |                | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | i am learning path, Learning Pathway 2, max-test-052417, Clinical Operations Acute Care Hospital Model 2                                                                                                                                                 |
      #| Login with Remedy Executive and verify Product Tiles and their redirections                  | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | Remedy Executive                  | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Reporting, Program Management               | Care Connect, Administration                                                                                                                  | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Mountainview Hospital, Stamford Hospital                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                          |
      #| Login with Prospective Partner Executive and verify Product Tiles and their redirections   | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | Prospective Partner Executive   | Remedy University, Care Innovation Institute                                                                                                                              | Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Community Connect, Care Connect, Reporting, Administration, Program Management |                | Patient ID     | Episode DRG Issues           |      | Presence Saint Joseph Medical Center, Evanston Hospital                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                          |
      | Login with Remedy Other and verify Product Tiles and their redirections                      | Super Admin | FirstName                                 | LastName                                 | Remedy Other                      | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Care Innovation Institute, Remedy University, Reporting Classic, Community Connect, Care Connect, Reporting, Program Management | Administration                                                                                                                                | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | New learning Path, Physician Acute Care Hospital Model 2                                                                                                                                                                                                 |
      #| Login with Partner Program Administrator and verify Product Tiles and their redirections     | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | Partner Program Administrator     | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Episode Connect for Post-acute Care, Care Innovation Institute                                                                 | Community Connect, Care Connect, Reporting, Administration, Program Management                                                                | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | i am learning path, Learning Pathway 2, max-test-052417, Physician Acute Care Hospital Model 2, Remedy University                                                                                                                                        |
      #| Login with Remedy Program Administrator and verify Product Tiles and their redirections      | Super Admin | FirstName                                 | LastName                                 | Remedy Program Administrator      | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Reporting                                                      | Community Connect, Care Connect, Administration, Program Management                                                                           | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Anderson, Bethlehem, Stamford Hospital, Albany Memorial Hospital, Saint Francis Hospital                                                                                                                                                                                                                                                                                              | i am learning path, Learning Pathway 2, max-test-052417, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University                                                                                                 |
      #| Login with Partner Technical Administrator and verify Product Tiles and their redirections   | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | Partner Technical Administrator   | Episode Connect, Episode Connect Classic, Reporting Classic, Administration, Remedy University, Reporting, Care Innovation Institute                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Program Management                                                      | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Presence Saint Joseph Medical Center, Mountainview Hospital, Vaughan Regional Medical Center Parkway Campus, San Mateo Medical Center, Aroostook Medical Center, Mayo Clinic Health System - Mankato, St Vincent Healthcare, St Rose Dominican Hospitals - Rose De Lima Campus, Desert Springs Hosp MC, Summerlin Hospital Medical Center, St Rose Dominican Hospitals - Siena Campus | Learning Pathway 2, New learning Path, Remedy University                                                                                                                                                                                                 |
      #| Login with Remedy Technical Administrator and verify Product Tiles and their redirections    | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | Remedy Technical Administrator    | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Administration, Care Innovation Institute, Remedy University                                                 | Community Connect, Care Connect, Program Management                                                                                           | ROLE_ADMIN     | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University |
      #| Login with Operator and verify Product Tiles and their redirections                          | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | Operator                          | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                                      | ROLE_TCS       | Patient ID     | Episode DRG Issues |      | Bethlehem, Anderson, Warren Hospital                                                                                                                                                                                                                                                                                                                                                  | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University |
      #| Login with Remedy Sales Acute Demo 2018 and verify Product Tiles and their redirections      | Super Admin | FirstName                                 | LastName                                 | Remedy Sales Acute Demo 2018      | Episode Connect, Care Innovation Institute, Episode Connect Classic, Reporting Classic, Remedy University, Episode Connect for Post-acute Care                                                                 | Community Connect, Care Connect, Administration, Program Management, Reporting                                                                | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Anderson                                                                                                                                                                                                                                                                                                                                                                              | Physician Acute Care Hospital Model 2, Remedy University                                                                                                                                                                                                 |
      #| Login with Remedy Sales PAC Demo 2018 and verify Product Tiles and their redirections        | Super Admin | FirstName                                 | LastName                                 | Remedy Sales PAC Demo 2018        | Episode Connect, Care Innovation Institute, Episode Connect Classic, Episode Connect for Post-acute Care                                                                                                       | Community Connect, Care Connect, Administration, Program Management, Reporting, Reporting Classic, Remedy University                          | ROLE_SNF       | Patient ID     | Episode DRG Issues |      | Anderson, Bethlehem                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                          |
      #| Login with Remedy Sales Commercial Demo 2018 and verify Product Tiles and their redirections | Super Admin | FirstName                                 | LastName                                 | Remedy Sales Commercial Demo 2018 | Episode Connect, Care Innovation Institute, Episode Connect for Post-acute Care                                                                                                                                | Community Connect, Care Connect, Administration, Program Management, Reporting, Reporting Classic, Remedy University, Episode Connect Classic |                | Patient ID     | Episode DRG Issues |      | Anderson, Bethlehem                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                          |

  #Scenario: Verify NPI on the EC1 tile
    #Given I am on the login page
    #When I enter email field qa.admin@yopmail.com for login
    #And I enter password field Episode1! for Login
    #And I click Access button
    #And I click on Episode1 tile for "Super Admin-Physicians" user
    #And I switch to new window
    #And I verify "Dashboard" after redirection to EC1 for "Super Admin-Physicians" user
    #And I verify NPI on ECI for "Super Admin-Physicians" user
