Feature: Create user having full application access- Super Admin User

Scenario Outline: Create User through UA API call
    Given Build JSON for Create User "<FirstName>" and "<LastName>" and "<Email>" and "<Phone>" and "<NPI>" and "<RoleID>" and "<Applications>" and "<Locations>" and "<LearningPathways>"
    When Create User with this data for "<User>"
    Then Verify Actual vs expected results "<expStatusCode>" and "<responseMsg>"
    Given I am on mail login page
    Then I enter username "qaautomation@remedysystems.com" to login mail account
    Then I enter password "9h$00v3T$dF@OPn0" to login mail account
    Then I click on Mail icon in my account
    Then I click on Inbox in mail
    And I wait for 3000 milli seconds
    Then I verify account for user "<User>-<Role>"
    Then I set new password for the user "<User>-<Role>"

    Examples: 
      | User        | FirstName                                 | LastName                                 | Email                          | Phone      | NPI | RoleID                             | Applications                                                                                                                                                                                                                                                                                                    | LearningPathways                                                                                                     | Locations                                                                                                                                                                                                                                                                                                                                                                  | expStatusCode |
      | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            |     | 1-Leader                           | episode_connect-Episode Connect Classic, reports-Reporting Classic, lessons-Remedy University, analytics-Reporting                                                                                                                                                                                              | 3hSOHNAnvjc1,NFdw0Kts2C01,n9yn5n0Qa581                                                                               | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      | Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 2-Manager                          | episode_connect-Episode Connect Classic, reports-Reporting Classic, lessons-Remedy University, analytics-Reporting                                                                                                                                                                                              | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,qfy2xp8zSFc1,18h7phZr1h81                                                     | 441324--6005-059--140007, 441324--6005-059--140010, 441324--3090-068--290039                                                                                                                                                                                                                                                                                               |           200 |
      | Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com | 9988776655 |     | 3-Advanced Operator                | episode_connect-Episode Connect Classic, reports-Reporting Classic, lessons-Remedy University, analytics-Reporting                                                                                                                                                                                              | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,5HDc3E6aK_E1                                                                  | 514029--2070-025--390326, 514029--2070-028--310060                                                                                                                                                                                                                                                                                                                         |           200 |
      | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            | NPI | 4-Physicians                       | episode_connect-Episode Connect Classic, reports-Reporting Classic, lessons-Remedy University, analytics-Reporting                                                                                                                                                                                              | 3hSOHNAnvjc1,18h7phZr1h81,n9yn5n0Qa581                                                                               | 439120--2070-c82--FWD, 439120--2070-c83--HCH                                                                                                                                                                                                                                                                                                                               |           200 |
      | Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 5-Remedy TCS                       | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University, community_connect-Community Connect, care_connect-Care Connect                                                             | NFdw0Kts2C01,jusUV22erpk1,p11D0Vl2FSg1,18h7phZr1h81,n9yn5n0Qa581                                                     | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            |     | 6-Remedy LPN                       | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University                                                                                                                             |                                                                                                                      | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      | Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com | 9988776655 |     | 7-Remedy RN                        | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University, community_connect-Community Connect, care_connect-Care Connect                                                             | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,HZhmTBQzHtU1,5HDc3E6aK_E1,p11D0Vl2FSg1,qfy2xp8zSFc1,18h7phZr1h81,n9yn5n0Qa581 | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedysystems.com |            |     | 8-Remedy Field RN                  | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University                                                                                                                             | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,HZhmTBQzHtU1,5HDc3E6aK_E1,p11D0Vl2FSg1,qfy2xp8zSFc1,18h7phZr1h81              | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      | Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 9-Remedy PM                        | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University                                                                                                                             | NFdw0Kts2C01,HZhmTBQzHtU1,p11D0Vl2FSg1,qfy2xp8zSFc1                                                                  | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      | Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 11-Remedy Sales Team               | reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University                                                                                                                                                                                                                             | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,p11D0Vl2FSg1                                                                  | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedysystems.com | 9988776655 |     | 14-Remedy Executive                | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University, community_connect-Community Connect, analytics-Reporting, program_management-Program Management                            | jusUV22erpk1,HZhmTBQzHtU1,n9yn5n0Qa581                                                                               | 441324--3090-068--290039, 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                            |           200 |
      | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            |     | 15-Prospective Partner Executive   | lessons-Remedy University                                                                                                                                                                                                                                                                                       | jusUV22erpk1,HZhmTBQzHtU1,n9yn5n0Qa581                                                                               | 441324--6005-059--140007, 441324--6005-059--140010                                                                                                                                                                                                                                                                                                                         |           200 |
      | Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 17-Remedy Other                    | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, tci-Care Innovation Institute, lessons-Remedy University, reports-Reporting Classic, community_connect-Community Connect, care_connect-Care Connect, analytics-Reporting, program_management-Program Management | HZhmTBQzHtU1,18h7phZr1h81                                                                                            | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedysystems.com |            |     | 18-Partner Program Administrator   | episode_connect-Episode Connect Classic, reports-Reporting Classic, lessons-Remedy University, episode_connect_2-Episode Connect for Post-acute Care                                                                                                                                                            | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,18h7phZr1h81,n9yn5n0Qa581                                                     | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      | Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com | 9988776655 |     | 19-Remedy Program Administrator    | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University, analytics-Reporting                                                                                                        | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,qfy2xp8zSFc1,18h7phZr1h81,n9yn5n0Qa581                                        | 439120--2070-c83--HCH, 439120--2070-c83--100073-REH, 439120--2070-c85--220066-IRF, 439120--2070-c85--MMC, 514083--2070-015--TSH, 514029--2070-025--390326, 514029--2070-028--310060                                                                                                                                                                                        |           200 |
      | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            |     | 20-Partner Technical Administrator | episode_connect-Episode Connect Classic, reports-Reporting Classic, admin-Administration, lessons-Remedy University, analytics-Reporting                                                                                                                                                                        | NFdw0Kts2C01,HZhmTBQzHtU1,n9yn5n0Qa581                                                                               | 441324--6005-059--140007, 441324--3090-068--290039, 441324--3090-191--290039, 441324--3090-068--010118, 441324--3090-068--050113, 441324--3090-068--200018, 441324--3090-068--240093, 441324--3090-068--270049, 441324--3090-068--290012, 441324--3090-068--290021, 441324--3090-068--290022, 441324--3090-068--290041, 441324--3090-068--290045, 441324--3090-068--290046 |           200 |
      | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedysystems.com | 9988776655 |     | 21-Remedy Technical Administrator  | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, admin-Administration, tci-Care Innovation Institute, lessons-Remedy University                                                                                                       | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,HZhmTBQzHtU1,5HDc3E6aK_E1,p11D0Vl2FSg1,qfy2xp8zSFc1,18h7phZr1h81,n9yn5n0Qa581 | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            |     | 22-Operator                        | episode_connect-Episode Connect Classic, reports-Reporting Classic, lessons-Remedy University, analytics-Reporting                                                                                                                                                                                              | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,HZhmTBQzHtU1,5HDc3E6aK_E1,p11D0Vl2FSg1,qfy2xp8zSFc1,18h7phZr1h81,n9yn5n0Qa581 | 514029--2070-028--310060, 514029--2070-025--390326                                                                                                                                                                                                                                                                                                                         |           200 |


  Scenario Outline: <Description>
    Given I am on the login page
    Then I enter newuser email for "<User>-<Role>" login to Remedy
    Then I enter newuser password for login to Remedy
    And I click Access button
    Then I verify "<Applications>" product on SPOE page
    Then I verify "<ApplicationsNotVisible>" product is not visible on SPOE page
    #######Episode Connect Classic Provisioning################
    And I click on Episode1 tile for "<User>-<Role>" user
    And I verify "Dashboard" after redirection to EC1 for "<User>-<Role>" user
    And I click on username icon on right top corner "<User>-<Role>" and open user profile on EC1
    And I verify "<Facilities>" facility on user profile for "<User>-<Role>" user
    And I verify "Not Associated" payer on user profile for "<User>-<Role>" user
    And I verify "Medicare" payer on user profile for "<User>-<Role>" user
    And I should not see "Emblem" payer on user profile for "<User>-<Role>" user
    And I click on PatientList on SideMenu bar Episode1 for "<User>-<Role>" user
    And I verify Patient card appearing on Active Patients page for "<User>-<Role>" user
    And I click on gear menu and then click on Add Note and verify user role "<Roletext>" for "<User>-<Role>" user
    And I redirect to Remedy connect page
    ###########Reporting Classic Provisioning##############
    And I click on Reports tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Reports homepage
    And I click on the Reports Tile with text "<ReportCategory>" for "<User>-<Role>" user
    Then I click on "<ReportName>" report text for Overall Program Reports for "<User>-<Role>" user
    Then I verify "<ReportName>" on the reports main page for "<User>-<Role>" user
    And I redirect to Remedy connect page
    ###############Reporting Provisioning###################################
    #And I click on Reporting tile for "<User>-<Role>" user
    #And I verify "<User>-<Role>" user navigated to Reporting homepage
    #And I redirect to Remedy connect page
    ###########Episode Connect Post Acute Care Provisioning##############
    And I click on Episodes 2 tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Episodes 2 homepage
    And I verify patient card appearing on Episode 2 for "<User>-<Role>" user
    And I redirect to Remedy connect page
    ############Remedy University Provisioning###############
    And I click on RemedyU tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to RemedyU homepage
    And I verify details "<FirstName> <LastName>" for "<User>-<Role>" user on RemedyU dashboard
    And I verify learning pathway "<LearningPathway>" appearing for "<User>-<Role>" user on RemedyU dashboard
    And I redirect to Remedy connect page
    ############User Admin Provisioning###################################
    And I click on User Admin tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to User Admin homepage
    And I redirect to Remedy connect page
    #############TCI Provisioning####################################
    #And I click on Institute tile for "<User>-<Role>" user
    #And I verify "<User>-<Role>" user navigated to Institute homepage
    #And I redirect to Remedy connect page
    #################Program Management Tile Provisioning####################
    And I click on Program Management tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Program Management homepage
    And I redirect to Remedy connect page
    #################Care Connect Tile Provisioning####################
    And I click on Care Connect tile for  "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Care Connect homepage
    And I redirect to Remedy connect page
    #################Community Connect Tile Provisioning####################
    And I click on Community Connect tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Community Connect homepage
    And I redirect to Remedy connect page
    #################General Verification################################
    And I click on the top user account link on remedy connect page
    And I verify "Support" in dropdown on profile icon for "<User>-<Role>" user
    And I verify "Reset Password" in dropdown on profile icon for "<Role>" user
    And I verify "Log Out" in dropdown on profile icon for "<Role>" user
    And I click on "Support" in dropdown on profile icon for "<User>-<Role>" user
    And I verify page header "Login" for "Support" on Remedy Connect for "<User>-<Role>" user
    Then I select Reset Password option from the dropdown
    And I should see text popup for reset password "We have sent you an e-mail with a link to reset your password."
    And I click Okay button for reset password popup
    Then I select Log Out option from the dropdown
    And I should see Log in widget

    Examples: 
      | Description                                                             | User        | FirstName | LastName | Role         | Applications                                                                                                                                                                                                   | ApplicationsNotVisible | Roletext | ReportCategory | ReportName         | BPID | Facilities        | LearningPathway                                          |
      | Login with Leader and verify Product Tiles and their redirections                          | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName | Leader                          | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                          | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | i am learning path, Learning Pathway 2, Remedy University                                                                                                                                                                                                |
      | Login with Manager and verify Product Tiles and their redirections                         | Super Admin | FirstName                                 | LastName                                 | Manager                         | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                          | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Presence Saint Joseph Medical Center, Evanston Hospital, Mountainview Hospital                                                                                                                                                                                                                                                                                                        | i am learning path, Learning Pathway 2, max-test-052417, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2                                                                                                                    |
      | Login with Advanced Operator and verify Product Tiles and their redirections               | Super Admin | FirstName                                 | LastName                                 | Advanced Operator               | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                          | ROLE_TCS       | Patient ID     | Episode DRG Issues |      |                                                                                                                                                                                                                                                                                                                                                                                       | i am learning path, Learning Pathway 2, max-test-052417, Care Coordination External                                                                                                                                                                      |
      | Login with Physicians and verify Product Tiles and their redirections                      | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName | Physicians                      | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                          | ROLE_CLINICIAN | Patient ID     | Episode DRG Issues |      | Saint Francis Hospital - Wilmington, Holy Cross Hospital - Fort Lauderdale                                                                                                                                                                                                                                                                                                            | i am learning path, Physician Acute Care Hospital Model 2, Remedy University                                                                                                                                                                             |
      | Login with Remedy TCS and verify Product Tiles and their redirections                      | Super Admin | FirstName                                 | LastName                                 | Remedy TCS                      | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Care Connect                                | Administration, Program Management                                                                                                | ROLE_TCS       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | Learning Pathway 2, max-test-052417, Clinical Operations Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University                                                                                                           |
      | Login with Remedy LPN and verify Product Tiles and their redirections                      | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | Remedy LPN                      | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University                                                                 | Community Connect, Care Connect, Administration, Program Management                                                               | ROLE_LPN       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                          |
      | Login with Remedy RN and verify Product Tiles and their redirections                       | Super Admin | FirstName                                 | LastName                                 | Remedy RN                       | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Care Connect                                | Administration, Program Management                                                                                                | ROLE_RN        | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University |
      | Login with Remedy Field RN and verify Product Tiles and their redirections                 | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | Remedy Field RN                 | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University                                                                 | Community Connect, Care Connect, Administration, Program Management                                                               | ROLE_FRN       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2                    |
      | Login with Remedy PM and verify Product Tiles and their redirections                       | Super Admin | FirstName                                 | LastName                                 | Remedy PM                       | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University                                                                 | Community Connect, Care Connect, Administration, Program Management                                                               | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | Learning Pathway 2, New learning Path, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2                                                                                                                            |
      | Login with Remedy Sales Team and verify Product Tiles and their redirections               | Super Admin | FirstName                                 | LastName                                 | Remedy Sales Team               | Episode Connect, Reporting Classic, Care Innovation Institute, Remedy University                                                                                                                               | Episode Connect Classic, Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management |                | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | i am learning path, Learning Pathway 2, max-test-052417, Clinical Operations Acute Care Hospital Model 2                                                                                                                                                 |
      | Login with Remedy Executive and verify Product Tiles and their redirections                | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | Remedy Executive                | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Reporting, Program Management               | Care Connect, Administration                                                                                                      | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Mountainview Hospital, Stamford Hospital                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                          |
      #| Login with Prospective Partner Executive and verify Product Tiles and their redirections   | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | Prospective Partner Executive   | Remedy University, Care Innovation Institute                                                                                                                              | Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Community Connect, Care Connect, Reporting, Administration, Program Management |                | Patient ID     | Episode DRG Issues           |      | Presence Saint Joseph Medical Center, Evanston Hospital                                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                          |
      | Login with Remedy Other and verify Product Tiles and their redirections | Super Admin | FirstName | LastName | Remedy Other | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Care Innovation Institute, Remedy University, Reporting Classic, Community Connect, Care Connect, Reporting, Program Management | Administration         | ROLE_PRM | Patient ID     | Episode DRG Issues |      | Stamford Hospital | New learning Path, Physician Acute Care Hospital Model 2 |
      | Login with Partner Program Administrator and verify Product Tiles and their redirections   | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | Partner Program Administrator   | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Episode Connect for Post-acute Care, Care Innovation Institute                                                                 | Community Connect, Care Connect, Reporting, Administration, Program Management                                                    | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | i am learning path, Learning Pathway 2, max-test-052417, Physician Acute Care Hospital Model 2, Remedy University                                                                                                                                        |
      | Login with Remedy Program Administrator and verify Product Tiles and their redirections    | Super Admin | FirstName                                 | LastName                                 | Remedy Program Administrator    | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Reporting                                                      | Community Connect, Care Connect, Administration, Program Management                                                               | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Weldon IRF at The Mercy Hospital, Mercy Medical Center - Springfield, Holy Cross Hospital - Fort Lauderdale, Holy Cross Rehabilitation Institute, Stamford Hospital                                                                                                                                                                                                                   | i am learning path, Learning Pathway 2, max-test-052417, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University                                                                                                 |
      | Login with Partner Technical Administrator and verify Product Tiles and their redirections | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | Partner Technical Administrator | Episode Connect, Episode Connect Classic, Reporting Classic, Administration, Remedy University, Reporting, Care Innovation Institute                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Program Management                                          | ROLE_PRM       | Patient ID     | Episode DRG Issues |      | Presence Saint Joseph Medical Center, Mountainview Hospital, Vaughan Regional Medical Center Parkway Campus, San Mateo Medical Center, Aroostook Medical Center, Mayo Clinic Health System - Mankato, St Vincent Healthcare, St Rose Dominican Hospitals - Rose De Lima Campus, Desert Springs Hosp MC, Summerlin Hospital Medical Center, St Rose Dominican Hospitals - Siena Campus | Learning Pathway 2, New learning Path, Remedy University                                                                                                                                                                                                 |
      | Login with Remedy Technical Administrator and verify Product Tiles and their redirections  | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | Remedy Technical Administrator  | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Administration, Care Innovation Institute, Remedy University                                                 | Community Connect, Care Connect, Program Management                                                                               | ROLE_ADMIN     | Patient ID     | Episode DRG Issues |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University |
      | Login with Operator and verify Product Tiles and their redirections                        | Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | Operator                        | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           | Episode Connect for Post-acute Care, Community Connect, Care Connect, Administration, Program Management                          | ROLE_TCS       | Patient ID     | Episode DRG Issues |      | Bethlehem, Anderson, Warren Hospital                                                                                                                                                                                                                                                                                                                                                  | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University |
