Feature: View User - Super Admin User

  Scenario Outline: Create User through UA API call
    Given Build JSON for Create User "<FirstName>" and "<LastName>" and "<Email>" and "<Phone>" and "<NPI>" and "<RoleID>" and "<Applications>" and "<Locations>" and "<LearningPathways>"
    When Create User with this data for "<User>"
    Then Verify Actual vs expected results "<expStatusCode>" and "<responseMsg>"

    Examples: 
      | User        | FirstName                                 | LastName                                 | Email                          | Phone      | NPI | RoleID                               | Applications                                                                                                                                                                                                                                                                                                    | LearningPathways                                                                                                     | Locations                                                                                                                                                                                                                                                                                                                                                                  | expStatusCode |
      | Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            |     | 1-Leader                             | episode_connect-Episode Connect Classic, reports-Reporting Classic, lessons-Remedy University, analytics-Reporting                                                                                                                                                                                              | 3hSOHNAnvjc1,NFdw0Kts2C01,n9yn5n0Qa581                                                                               | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      | Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 2-Manager                            | episode_connect-Episode Connect Classic, reports-Reporting Classic, lessons-Remedy University, analytics-Reporting                                                                                                                                                                                              | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,qfy2xp8zSFc1,18h7phZr1h81                                                     | 441324--6005-059--140007, 441324--6005-059--140010, 441324--3090-068--290039                                                                                                                                                                                                                                                                                               |           200 |
      #| Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com | 9988776655 |     | 3-Advanced Operator                  | episode_connect-Episode Connect Classic, reports-Reporting Classic, lessons-Remedy University, analytics-Reporting                                                                                                                                                                                              | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,5HDc3E6aK_E1                                                                  | 514029--2070-025--390326, 514029--2070-028--310060                                                                                                                                                                                                                                                                                                                         |           200 |
      #| Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            | NPI | 4-Physicians                         | episode_connect-Episode Connect Classic, reports-Reporting Classic, lessons-Remedy University, analytics-Reporting                                                                                                                                                                                              | 3hSOHNAnvjc1,18h7phZr1h81,n9yn5n0Qa581                                                                               | 439120--2070-c82--FWD, 439120--2070-c90--ALB                                                                                                                                                                                                                                                                                                                               |           200 |
      #| Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 5-Remedy TCS                         | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University, community_connect-Community Connect, care_connect-Care Connect                                                             | NFdw0Kts2C01,jusUV22erpk1,p11D0Vl2FSg1,18h7phZr1h81,n9yn5n0Qa581                                                     | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      #| Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            |     | 6-Remedy LPN                         | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University                                                                                                                             |                                                                                                                      | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      #| Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com | 9988776655 |     | 7-Remedy RN                          | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University, community_connect-Community Connect, care_connect-Care Connect                                                             | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,HZhmTBQzHtU1,5HDc3E6aK_E1,p11D0Vl2FSg1,qfy2xp8zSFc1,18h7phZr1h81,n9yn5n0Qa581 | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      #| Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedysystems.com |            |     | 8-Remedy Field RN                    | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University                                                                                                                             | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,HZhmTBQzHtU1,5HDc3E6aK_E1,p11D0Vl2FSg1,qfy2xp8zSFc1,18h7phZr1h81              | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      #| Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 9-Remedy PM                          | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University                                                                                                                             | NFdw0Kts2C01,HZhmTBQzHtU1,p11D0Vl2FSg1,qfy2xp8zSFc1                                                                  | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      #| Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 11-Remedy Sales Team                 | reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University                                                                                                                                                                                                                             | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,p11D0Vl2FSg1                                                                  | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      #| Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedysystems.com | 9988776655 |     | 14-Remedy Executive                  | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University, community_connect-Community Connect, analytics-Reporting, program_management-Program Management                            | jusUV22erpk1,HZhmTBQzHtU1,n9yn5n0Qa581                                                                               | 441324--3090-068--290039, 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                            |           200 |
      #| Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            |     | 15-Prospective Partner Executive     | lessons-Remedy University                                                                                                                                                                                                                                                                                       | jusUV22erpk1,HZhmTBQzHtU1,n9yn5n0Qa581                                                                               | 441324--6005-059--140007, 441324--6005-059--140010                                                                                                                                                                                                                                                                                                                         |           200 |
      #| Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 17-Remedy Other                      | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, tci-Care Innovation Institute, lessons-Remedy University, reports-Reporting Classic, community_connect-Community Connect, care_connect-Care Connect, analytics-Reporting, program_management-Program Management | HZhmTBQzHtU1,18h7phZr1h81                                                                                            | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      #| Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedysystems.com |            |     | 18-Partner Program Administrator     | episode_connect-Episode Connect Classic, reports-Reporting Classic, lessons-Remedy University, episode_connect_2-Episode Connect for Post-acute Care                                                                                                                                                            | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,18h7phZr1h81,n9yn5n0Qa581                                                     | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      #| Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com | 9988776655 |     | 19-Remedy Program Administrator      | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University, analytics-Reporting                                                                                                        | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,qfy2xp8zSFc1,18h7phZr1h81,n9yn5n0Qa581                                        | 439120--2070-c82--FWD, 439120--2070-c90--ALB, 514083--2070-015--TSH, 514029--2070-025--390326, 514029--2070-028--310060                                                                                                                                                                                                                                                    |           200 |
      #| Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            |     | 20-Partner Technical Administrator   | episode_connect-Episode Connect Classic, reports-Reporting Classic, admin-Administration, lessons-Remedy University, analytics-Reporting                                                                                                                                                                        | NFdw0Kts2C01,HZhmTBQzHtU1,n9yn5n0Qa581                                                                               | 441324--6005-059--140007, 441324--3090-068--290039, 441324--3090-191--290039, 441324--3090-068--010118, 441324--3090-068--050113, 441324--3090-068--200018, 441324--3090-068--240093, 441324--3090-068--270049, 441324--3090-068--290012, 441324--3090-068--290021, 441324--3090-068--290022, 441324--3090-068--290041, 441324--3090-068--290045, 441324--3090-068--290046 |           200 |
      #| Super Admin | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | qaautomation@remedysystems.com | 9988776655 |     | 21-Remedy Technical Administrator    | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, admin-Administration, tci-Care Innovation Institute, lessons-Remedy University                                                                                                       | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,HZhmTBQzHtU1,5HDc3E6aK_E1,p11D0Vl2FSg1,qfy2xp8zSFc1,18h7phZr1h81,n9yn5n0Qa581 | 514083--2070-015--TSH                                                                                                                                                                                                                                                                                                                                                      |           200 |
      #| Super Admin | FirstName                                 | LastNameLastNameLastNameLastNameLastName | qaautomation@remedysystems.com |            |     | 22-Operator                          | episode_connect-Episode Connect Classic, reports-Reporting Classic, lessons-Remedy University, analytics-Reporting                                                                                                                                                                                              | 3hSOHNAnvjc1,NFdw0Kts2C01,jusUV22erpk1,HZhmTBQzHtU1,5HDc3E6aK_E1,p11D0Vl2FSg1,qfy2xp8zSFc1,18h7phZr1h81,n9yn5n0Qa581 | 514029--2070-028--310060, 514029--2070-025--390326                                                                                                                                                                                                                                                                                                                         |           200 |
      #| Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 26-Remedy Sales Acute Demo 2018      | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, reports-Reporting Classic, tci-Care Innovation Institute, lessons-Remedy University                                                                                                                             | 18h7phZr1h81, n9yn5n0Qa581                                                                                           | 514029--2070-025--T                                                                                                                                                                                                                                                                                                                                                        |           200 |
      #| Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 27-Remedy Sales PAC Demo 2018        | episode_connect-Episode Connect Classic, episode_connect_2-Episode Connect for Post-acute Care, tci-Care Innovation Institute                                                                                                                                                                                   |                                                                                                                      | 514029--2070-025--T, 514029--2070-023--L                                                                                                                                                                                                                                                                                                                                   |           200 |
      #| Super Admin | FirstName                                 | LastName                                 | qaautomation@remedysystems.com |            |     | 28-Remedy Sales Commercial Demo 2018 | episode_connect_2-Episode Connect for Post-acute Care, tci-Care Innovation Institute                                                                                                                                                                                                                            |                                                                                                                      | 514029--2070-025--T, 514029--2070-023--L                                                                                                                                                                                                                                                                                                                                   |           200 |

  #Scenario Outline: <Description>
    #Given I am on the login page
    #When I enter email field lbarinstein+qaadmin@remedypartners.com for login
    #And I enter password field Testing1 for Login
    #Then I click Access button
    #Then I should see Tile text Users
    #And I click on the "Users" tile
    #Then I should see header text "Users"
    #Then I search for user with role "<User>-<Role>"
    #Then I select user with role "<User>-<Role>"
    #And I verify that I am navigated to user page
    #Then I verify All Users button
    #Then I click on All Users button
    #Then I should see header text "Users"
    #Then I search for user with role "<User>-<Role>"
    #Then I select user with role "<User>-<Role>"
    #And I verify that I am navigated to user page
    #Then I verify Edit Icon
    #Then I click on Edit Icon
    #Then I verify Delete User button
    #Then I click on cross button on Edit User Page
    #Then I verify Lock/Unlock Icon
    #Then I verify first name "<FirstName>"
    #Then I verify last name "<LastName>"
    #Then I verify role "<Role>"
    #Then I verify email "Email" for "<User>-<Role>"
    #Then I verify phone "<Phone>"
    #Then I verify NPI "<NPI>"
    #Then I verify enabled "<ApplicationsEnabled>"
    #Then I verify disabled "<ApplicationsDisabled>"
    #Then I verify learning pathway "<LearningPathway>"
    #Then I verify health system "<HealthSystem>"
    #Then I verify programs "<Programs>"
    #Then I verify location "<Locations>"
#
    #Examples: 
      #| Description                                                               | User        | UserName                               | Password | FirstName                                 | LastName                                 | Phone        | Role                              | ApplicationsEnabled                                                                                                                                                                                            | ApplicationsDisabled | NPI | LearningPathway                                                                                                                                                                                                                                          | HealthSystem                                                           | Programs                                                                                              | Locations                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      #| View Leader user created from Super Admin user                            | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName |              | Leader                            | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           |                      |     | i am learning path, Learning Pathway 2, Remedy University                                                                                                                                                                                                | Stamford Hospital                                                      | Stamford Hospital--BPCI Model 2                                                                       | Stamford Hospital--2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      #| View Manager user created from Super Admin user                           | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 |              | Manager                           | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           |                      |     | i am learning path, Learning Pathway 2, max-test-052417, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2                                                                                                                    | Sound Physicians                                                       | Sound Physicians--BPCI Model 2, Sound Physicians--BPCI Model 3                                        | Sound Physicians--6005-059--Presence Saint Joseph Medical Center, Sound Physicians--6005-059--Evanston Hospital, Sound Physicians--3090-068--Mountainview Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      #| View Advanced Operator user created from Super Admin                      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | 998-877-6655 | Advanced Operator                 | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           |                      |     | i am learning path, Learning Pathway 2, max-test-052417, Care Coordination External                                                                                                                                                                      | St. Lukes Health Network, Inc. DBA St. Lukes University Health Network | St. Lukes Health Network--BPCI Model 2                                                                | St. Lukes Health Network--2070-025--ST LUKE'S HOSPITAL - ANDERSON CAMPUS, St. Lukes Health Network--2070-028--ST LUKE'S WARREN HOSPITAL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      #| View Physicians user created from Super Admin user                        | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName |              | Physicians                        | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           |                      |     | i am learning path, Physician Acute Care Hospital Model 2, Remedy University                                                                                                                                                                             | Trinity Health                                                         | Trinity Health--BPCI Model 2                                                                          | Trinity Health--2070-c82--Saint Francis Hospital, Trinity Health--2070-c90--Albany Memorial Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      #| View Remedy TCS user created from Super Admin user                        | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 |              | Remedy TCS                        | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Care Connect                                |                      |     | Learning Pathway 2, max-test-052417, Clinical Operations Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University                                                                                                           | Stamford Hospital                                                      | Stamford Hospital--BPCI Model 2                                                                       | Stamford Hospital--2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      #| View Remedy LPN user created from Super Admin user                        | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastNameLastNameLastNameLastNameLastName |              | Remedy LPN                        | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University                                                                 |                      |     |                                                                                                                                                                                                                                                          | Stamford Hospital                                                      | Stamford Hospital--BPCI Model 2                                                                       | Stamford Hospital--2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      #| View Remedy RN user created from Super Admin user                         | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | 998-877-6655 | Remedy RN                         | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Care Connect                                |                      |     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University | Stamford Hospital                                                      | Stamford Hospital--BPCI Model 2                                                                       | Stamford Hospital--2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      #| View Remedy Field RN user created from Super Admin user                   | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 |              | Remedy Field RN                   | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University                                                                 |                      |     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2                    | Stamford Hospital                                                      | Stamford Hospital--BPCI Model 2                                                                       | Stamford Hospital--2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      #| View Remedy PM user created from Super Admin user                         | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 |              | Remedy PM                         | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University                                                                 |                      |     | Learning Pathway 2, New learning Path, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2                                                                                                                            | Stamford Hospital                                                      | Stamford Hospital--BPCI Model 2                                                                       | Stamford Hospital--2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      #| View Remedy Sales Team user created from Super Admin user                 | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 |              | Remedy Sales Team                 | Episode Connect, Reporting Classic, Care Innovation Institute, Remedy University                                                                                                                               |                      |     | i am learning path, Learning Pathway 2, max-test-052417, Clinical Operations Acute Care Hospital Model 2                                                                                                                                                 | Stamford Hospital                                                      | Stamford Hospital--BPCI Model 2                                                                       | Stamford Hospital--2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      #| View Remedy Executive user created from Super Admin user                  | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | 998-877-6655 | Remedy Executive                  | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Community Connect, Reporting, Program Management               |                      |     | max-test-052417, New learning Path, Remedy University                                                                                                                                                                                                    | Sound Physicians, Stamford Hospital                                    | Sound Physicians--BPCI Model 3, Stamford Hospital--BPCI Model 2                                       | Sound Physicians--3090-068--Mountainview Hospital, Stamford Hospital--2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      #| View Prospective Partner Executive user created from Super Admin user     | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastNameLastNameLastNameLastNameLastName |              | Prospective Partner Executive     | Episode Connect, Remedy University, Care Innovation Institute                                                                                                                                                  |                      |     | max-test-052417, New learning Path, Remedy University                                                                                                                                                                                                    | Sound Physicians                                                       | Sound Physicians--BPCI Model 2                                                                        | Sound Physicians--6005-059--Presence Saint Joseph Medical Center, Sound Physicians--6005-059--Evanston Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      #| View Remedy Other user created from Super Admin user                      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 |              | Remedy Other                      | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Care Innovation Institute, Remedy University, Reporting Classic, Community Connect, Care Connect, Reporting, Program Management |                      |     | New learning Path, Physician Acute Care Hospital Model 2                                                                                                                                                                                                 | Stamford Hospital                                                      | Stamford Hospital--BPCI Model 2                                                                       | Stamford Hospital--2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      #| View Partner Program Administrator user created from Super Admin user     | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 |              | Partner Program Administrator     | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Episode Connect for Post-acute Care, Care Innovation Institute                                                                 |                      |     | i am learning path, Learning Pathway 2, max-test-052417, Physician Acute Care Hospital Model 2, Remedy University                                                                                                                                        | Stamford Hospital                                                      | Stamford Hospital--BPCI Model 2                                                                       | Stamford Hospital--2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      #| View Remedy Program Administrator user created from Super Admin user      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 | 998-877-6655 | Remedy Program Administrator      | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Care Innovation Institute, Remedy University, Reporting                                                      |                      |     | i am learning path, Learning Pathway 2, max-test-052417, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University                                                                                                 | Trinity Health,  Stamford Hospital, St. Lukes Health Network           | Trinity Health--BPCI Model 2, Stamford Hospital--BPCI Model 2, St. Lukes Health Network--BPCI Model 2 | Trinity Health--2070-c82--Saint Francis Hospital, Trinity Health--2070-c90--Albany Memorial Hospital, Stamford Hospital--2070-015--Stamford Hospital, St. Lukes Health Network--2070-025--ST LUKE'S HOSPITAL - ANDERSON CAMPUS, St. Lukes Health Network--2070-028--ST LUKE'S WARREN HOSPITAL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      #| View Partner Technical Administrator user created from Super Admin user   | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastNameLastNameLastNameLastNameLastName |              | Partner Technical Administrator   | Episode Connect, Episode Connect Classic, Reporting Classic, Administration, Remedy University, Reporting, Care Innovation Institute                                                                           |                      |     | Learning Pathway 2, New learning Path, Remedy University                                                                                                                                                                                                 | Sound Physicians                                                       | Sound Physicians--BPCI Model 2, Sound Physicians--BPCI Model 3                                        | Sound Physicians--6005-059--Presence Saint Joseph Medical Center, Sound Physicians--3090-068--Mountainview Hospital, Sound Physicians--3090-191--Mountainview Hospital, Sound Physicians--3090-068--Vaughan Regional Medical Center Parkway Campus, Sound Physicians--3090-068--San Mateo Medical Center, Sound Physicians--3090-068--Aroostook Medical Center, Sound Physicians--3090-068--Mayo Clinic Health System - Mankato, Sound Physicians--3090-068--St Vincent Healthcare, Sound Physicians--3090-068--St Rose Dominican Hospitals - Rose De Lima Campus, Sound Physicians--3090-068--Valley Hospital Medical Center, Sound Physicians--3090-068--Desert Springs Hosp MC, Sound Physicians--3090-068--Summerlin Hospital Medical Center, Sound Physicians--3090-068--St Rose Dominican Hospitals - Siena Campus, Sound Physicians--3090-068--Spring Valley Hospital Medical Center |
      #| View Remedy Technical Administrator user created from Super Admin user    | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastName                                 | 998-877-6655 | Remedy Technical Administrator    | Episode Connect, Episode Connect Classic, Episode Connect for Post-acute Care, Reporting Classic, Administration, Care Innovation Institute, Remedy University                                                 |                      |     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University | Stamford Hospital                                                      | Stamford Hospital--BPCI Model 2                                                                       | Stamford Hospital--2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      #| View Operator user created from Super Admin user                          | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastNameLastNameLastNameLastNameLastName |              | Operator                          | Episode Connect, Episode Connect Classic, Reporting Classic, Remedy University, Reporting, Care Innovation Institute                                                                                           |                      |     | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University | St. Lukes Health Network, Inc. DBA St. Lukes University Health Network | St. Lukes Health Network--BPCI Model 2                                                                | St. Lukes Health Network--2070-028--ST LUKE'S WARREN HOSPITAL, St. Lukes Health Network--2070-025--ST LUKE'S HOSPITAL - ANDERSON CAMPUS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      #| View Remedy Sales Acute Demo 2018 user created from Super Admin user      | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 |              | Remedy Sales Acute Demo 2018      | Episode Connect, Care Innovation Institute, Episode Connect Classic, Reporting Classic, Remedy University, Episode Connect for Post-acute Care                                                                 |                      |     | Physician Acute Care Hospital Model 2, Remedy University                                                                                                                                                                                                 | St. Lukes Health Network, Inc. DBA St. Lukes University Health Network | St. Lukes Health Network--BPCI Model 2                                                                | St. Lukes Health Network--2070-025--Anderson                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      #| View Remedy Sales PAC Demo 2018 user created from Super Admin user        | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 |              | Remedy Sales PAC Demo 2018        | Episode Connect, Care Innovation Institute, Episode Connect Classic, Episode Connect for Post-acute Care                                                                                                       |                      |     |                                                                                                                                                                                                                                                          | St. Lukes Health Network, Inc. DBA St. Lukes University Health Network | St. Lukes Health Network--BPCI Model 2                                                                | St. Lukes Health Network--2070-025--Anderson, St. Lukes Health Network--2070-023--Bethlehem                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      #| View Remedy Sales Commercial Demo 2018 user created from Super Admin user | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstName                                 | LastName                                 |              | Remedy Sales Commercial Demo 2018 | Episode Connect, Care Innovation Institute, Episode Connect for Post-acute Care                                                                                                                                |                      |     |                                                                                                                                                                                                                                                          | St. Lukes Health Network, Inc. DBA St. Lukes University Health Network | St. Lukes Health Network--BPCI Model 2                                                                | St. Lukes Health Network--2070-025--Anderson, St. Lukes Health Network--2070-023--Bethlehem                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |

  Scenario Outline: Verifying that Blank page is not displayed on refreshing the User view page
    Given I am on the login page
    When I enter email field lbarinstein+qaadmin@remedypartners.com for login
    And I enter password field Testing1 for Login
    Then I click Access button
    Then I should see Tile text Users
    And I click on the "Users" tile
    Then I should see header text "Users"
    Then I search for user with role "<User>-<Role>"
    Then I select user with role "<User>-<Role>"
    And I verify that I am navigated to user page
    Then I refresh the view user page
    And I verify that I am navigated to user page
    Then I verify All Users button
    Then I click on All Users button
    Then I should see header text "Users"
    Then I search for user with role "<User>-<Role>"
    Then I select user with role "<User>-<Role>"
    And I verify that I am navigated to user page
    Then I verify Edit Icon
    Then I click on Edit Icon
    Then I select "Permissions" tab
    Then I click Add Organization button for "<HasHealthSystem2>" flag
    And I search for health system with <Health System2>
    And I select a <Health System2>
    Then I select "<Programs2>" programs
    Then I select "<Locations2>" locations
    Then I click on Submit button while edit for "<User>-<Role>"
    Then I refresh the view user page
    And I verify that I am navigated to user page
    Then I verify health system "<HealthSystemValidation>"
    Then I verify programs "<ProgramsValidation>"
    Then I verify location "<LocationsValidation>"

    Examples: 
      | Description                                       | User        | UserName                               | Password | FirstName                                 | LastName                                 | Phone | Role   | ApplicationsEnabled                                 | ApplicationsNotVisible                                                         | NPI | LearningPathway                                           | HasHealthSystem2 | Health System2 | Programs2    | Locations2                       | HealthSystemValidation            | ProgramsValidation                                            | LocationsValidation                                                                              |
      | View Executive user created from Super Admin user | Super Admin | lbarinstein+qaadmin@remedypartners.com | Testing1 | FirstNameFirstNameFirstNameFirstNameFirst | LastNameLastNameLastNameLastNameLastName |       | Leader | Episode Connect Classic, Reporting Classic, Lessons | Episode Connect for Post-acute Care, Administration, Care Innovation Institute |     | i am learning path, Learning Pathway 2, Remedy University | Yes              | Trinity Health | BPCI Model 2 | 2070-c82--Saint Francis Hospital | Stamford Hospital, Trinity Health | Stamford Hospital--BPCI Model 2, Trinity Health--BPCI Model 2 | Stamford Hospital--2070-015--Stamford Hospital, Trinity Health--2070-c82--Saint Francis Hospital |

  Scenario Outline: Lock/Unlock user from view user page
    Given I am on the login page
    When I enter email field lbarinstein+qaadmin@remedypartners.com for login
    And I enter password field Testing1 for Login
    Then I click Access button
    Then I should see Tile text Users
    And I click on the "Users" tile
    Then I should see header text "Users"
    Then I search for user with role "<User>-<Role>"
    Then I select user with role "<User>-<Role>"
    And I verify that I am navigated to user page
    Then I verify Lock/Unlock Icon
    Then I click on "Lock" icon on view user page
    Then I verify that user is "Locked" on view user page
    Then I click on "Unlock" icon on view user page
    Then I should see an alert with "Are you sure you want to unlock"
    Then I click on "Unlock" button from the unlock alert
    Then I verify that user is "Unlocked" on view user page

    Examples: 
      | User        | Role   | UserName                               | Password |
      | Super Admin | Leader | lbarinstein+qaadmin@remedypartners.com | Testing1 |

  Scenario Outline: Validating that Locations for the unselected Model are removed on view and edit user page
    Given I am on the login page
    When I enter email field lbarinstein+qaadmin@remedypartners.com for login
    And I enter password field Testing1 for Login
    Then I click Access button
    Then I should see Tile text Users
    And I click on the "Users" tile
    Then I should see header text "Users"
    Then I search for user with role "<User>-<Role>"
    Then I select user with role "<User>-<Role>"
    And I verify that I am navigated to user page
    And I click on Edit button
    Then I select "Permissions" tab
    Then I verify the header "Permissions"
    Then I click on existing organisation "<Health System>"
    Then I deselect "<RemovePrograms>" programs
    And I verify that "<RemovePrograms>" is not reflected as selected in edit user page
    Then I search the "<RemovedLocations>" in the Selected Locations section
    Then I verify No results found for invalid Location in selected organisation
    Then I click on Submit button while edit for "<User>-<Role>"
    Then I verify programs "<Programs>"
    Then I verify Program "<RemoveProgramsValidation>" is not present in view user page
    Then I verify location "<Locations>"
    Then I verify location "<RemovedLocationsValidation>" is not present on view page

    Examples: 
      | User        | Role    | Health System    | RemovePrograms | RemovedLocations                | RemovedLocationsValidation                        | Locations                                                                                                       | Programs                       | RemoveProgramsValidation       |
      | Super Admin | Manager | Sound Physicians | BPCI Model 3   | 3090-068--Mountainview Hospital | Sound Physicians--3090-068--Mountainview Hospital | Sound Physicians--6005-059--Presence Saint Joseph Medical Center, Sound Physicians--6005-059--Evanston Hospital | Sound Physicians--BPCI Model 2 | Sound Physicians--BPCI Model 3 |
