Feature: Upload Single User as per role from SA

  Scenario Outline: <Description>
    #Given I am on mail login page
    #Then I enter username "qaautomation@remedypartners.com" to login mail account for bulk delete
    #Then I enter password "1Welcome2" to login mail account
    #Then I click on Mail icon in my account
    #Then I click on Inbox in mail
    #Then I click on delete icon in mail
    #Then I signout from mail account
    Given I am on the login page
    Then I log in as super user
    Then I should see Tile text User Admin
    And I click on the "User Admin" tile
    Then I should see header text "Users"
    Then I click on Import User button
    Then I click on Try Again button
    Then I enter single user data with full application access for "<Role>"
    Then I click on submit button on bulk user upload page
    Then I verify "1 user added" message
    Then I verify availability of Hide button
    When I click on Hide button
    Then I should see header text "Users"
    Then I search for bulk user with role "<User>-<Role>"
    Then I verify user "<User>-<Role>" is added to users list
    Then I select user with role "<User>-<Role>"
    And I verify that I am navigated to user page
    Then I verify first name "<FirstName>"
    Then I verify last name "<LastName>"
    Then I verify role "<Role>"
    Then I verify email "<Email>" for "<User>-<Role>"
    Then I verify phone "<Phone>"
    Then I verify NPI "<NPI>"
    Then I verify enabled "<ApplicationsEnabled>"
    Then I verify health system "<HealthSystem>"
    Then I verify programs "<Programs>"
    Then I verify location "<Locations>"
    And I click on the top user account link
    Then I click on "Log Out" button
    Given I am on the login page
    Then I click on "Log Out" button again
    And I should see Log in widget
    Given I am on mail login page
    Then I enter username "qaautomation@remedypartners.com" to login mail account for bulk delete
    Then I enter password "1Welcome2" to login mail account
    Then I click on Mail icon in my account
    Then I click on Inbox in mail
    And I wait for 3000 milli seconds
    Then I verify Account Verification in Inbox in my account
    Then I click on Account Verification mail in Inbox
    Then I verify "Confirm my account!" link in mail content
    Then I click on "Confirm my account!" link in mail content
    And I switch to new window
    Then I enter email to generate password link
    And I click on send mail button
    Then I switch back to old window
    Then I click on Inbox in mail
    Then I verify the unread mail in inbox in my account
    Then I verify Change Password mail in Inbox in my account
    Then I click on Change Password mail in Inbox
    Then I verify "Change my password" link in mail content
    Then I click on "Change my password" link in mail content
    And I switch to new window
    And I enter new password "Testing1" to set new password
    And I enter confirm new password "Testing1" to set new password
    And I click on submit button to set new password
    Given I am on the login page
    Then I enter newuser email for "<User>-<Role>" login to Remedy
    Then I enter newuser password for login to Remedy
    And I click Access button
    Then I verify "<Applications>" product on SPOE page
    Then I verify "<ApplicationsNotVisible>" product is not visible on SPOE page
    Then I click on Hamburger menu on top left of homepage
    And I verify "<Applications>" in product menu dropdown
    And I verify "<ApplicationsNotVisible>" is not present in product menu dropdown
    And I redirect to Remedy connect page
    And I click on Episode1 tile for "<User>-<Role>" user
    And I switch to new window
    And I verify "Dashboard" after redirection to EC1 for "<User>-<Role>" user
    And I click on username icon on right top corner "<User>-<Role>" and open user profile on EC1
    And I verify "<Facilities>" facility on user profile for "<User>-<Role>" user
    And I verify "Not Associated" payer on user profile for "<User>-<Role>" user
    And I verify "Medicare" payer on user profile for "<User>-<Role>" user
    And I should not see "Emblem" payer on user profile for "<User>-<Role>" user
    And I click on PatientList on SideMenu bar Episode1 for "<User>-<Role>" user
    And I verify Patient card appearing on Active Patients page for "<User>-<Role>" user
    And I click on gear menu and then click on Add Note and verify user role "<Roletext>" for "<User>-<Role>" user
    And I switch back to old window
    And I click on Institute tile for "<User>-<Role>" user
    And I switch to new window
    And I verify "<User>-<Role>" user navigated to Institute homepage
    And I switch back to old window
    And I click on Reports tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Reports homepage
    And I click on the Reports Tile with text "<ReportCategory>" for "<User>-<Role>" user
    Then I click on "<ReportName>" report text for Overall Program Reports for "<User>-<Role>" user
    Then I verify "<ReportName>" on the reports main page for "<User>-<Role>" user
    #When I click on field-panel-icon button for "<User>-<Role>" user
    #When I click to "BPID" field filter under "Episode Initiator" filter field for "<User>-<Role>" user
    #And I choose "Filter" option from select options of filter field for "<User>-<Role>" user
    #And I should see "<BPID>" in the filter value list for "<User>-<Role>" user
    #And I click on cancel button from filter for "<User>-<Role>" user
    And I redirect to Remedy connect page
    And I click on Episodes 2 tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Episodes 2 homepage
    And I verify patient card appearing on Episode 2 for "<User>-<Role>" user
    And I click on RemedyU tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to RemedyU homepage
    And I verify details "<FirstName> <LastName>" for "<User>-<Role>" user on RemedyU dashboard
    #And I verify learning pathway "<LearningPathway>" appearing for "<User>-<Role>" user on RemedyU dashboard
    And I redirect to Remedy connect page
    And I click on Gainsharing Physician Survey tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to Gainsharing Physician Survey homepage
    And I redirect to Remedy connect page
    And I click on User Admin tile for "<User>-<Role>" user
    And I verify "<User>-<Role>" user navigated to User Admin homepage
    And I redirect to Remedy connect page
    And I click on the top user account link on remedy connect page
    And I verify "Support" in dropdown on profile icon for "<User>-<Role>" user
    And I verify "Reset Password" in dropdown on profile icon for "<Role>" user
    And I verify "Log Out" in dropdown on profile icon for "<Role>" user
    And I click on "Support" in dropdown on profile icon for "<User>-<Role>" user
    And I verify page header "Login" for "Support" on Remedy Connect for "<User>-<Role>" user
    Then I select Reset Password option from the dropdown
    And I should see text popup for reset password "We have sent you an e-mail with a link to reset your password."
    And I click Okay button for reset password popup
    Then I select Log Out option from the dropdown
    And I should see Log in widget

    Examples: 
      | Description                                                                       | User        | Role            | NPI | FirstName            | LastName            | Phone        | ApplicationsEnabled                           | ApplicationsDisabled | HealthSystem                 | Programs                                                                 | Locations                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | Applications                                       | ApplicationsNotVisible                          | Roletext       | ReportCategory | ReportName                   | BPID | Facilities                                                                                                                                                                                                                                                                                                                                                                                    | LearningPathway                                                                                                                                                                                                                                          |
      | Upload Executive, verify email, login with created user and validate tiles        | Super Admin | Executive       |     | ExecutiveFirstName   | ExecutiveLastName   |              | Episodes, Reports, Lessons                    |                      | Stamford Hospital            | Stamford Hospital--BPCI Model 2                                          | Stamford Hospital--2070-015--Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | Episodes, Reports, Lessons, TCI                    | Administration, Episodes 2.0, Physician Connect | ROLE_PRM       | Patient ID     | Episode DRG Issues           |      | Stamford Hospital                                                                                                                                                                                                                                                                                                                                                                             | i am learning path, Learning Pathway 2, Remedy University                                                                                                                                                                                                |
      | Upload Manager, verify email, login with created user and validate tiles          | Super Admin | Manager         |     | ManagerFirstName     | ManagerLastName     | 987-654-5678 | Episodes, Reports, Lessons                    |                      | Branford Hills               | Branford Hills--BPCI Model 3                                             | Branford Hills--3056-r29--Branford Hills Healthcare Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Episodes, Reports, Lessons, TCI                    | Administration, Episodes 2.0, Physician Connect | ROLE_PRM       | Patient ID     | Episode DRG Issues [Model 3] |      | Branford Hills Healthcare Center                                                                                                                                                                                                                                                                                                                                                              | i am learning path, Learning Pathway 2, max-test-052417, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2                                                                                                                    |
      | Upload Case Manager, verify email, login with created user and validate tiles     | Super Admin | Case Manager    |     | CaseManagerFirstName | CaseManagerLastName | 987-980-0980 | Episodes, Reports, Lessons                    |                      | Hackensack                   | Hackensack--BPCI Model 2                                                 | Hackensack--2070-005--Hackensack University Medical Center                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Episodes, Reports, Lessons, TCI                    | Administration, Episodes 2.0, Physician Connect | ROLE_TCS       | Patient ID     | Episode DRG Issues           |      | Hackensack University Medical Center                                                                                                                                                                                                                                                                                                                                                          | i am learning path, Learning Pathway 2, max-test-052417, Care Coordination External                                                                                                                                                                      |
      | Upload Physicians, verify email, login with created user and validate tiles       | Super Admin | Physicians      |     | PhysiciansFirstName  | PhysiciansLastName  |              | Episodes, Reports, Physician Connect, Lessons |                      | Hospital For Special Surgery | Hospital For Special Surgery--BPCI Model 2                               | Hospital For Special Surgery--2070-046--Hss - Hospital For Special Surgery                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Episodes, Reports, Physician Connect, TCI, Lessons | Administration, Episodes 2.0                    | ROLE_CLINICIAN | Patient ID     | Episode DRG Issues           |      | HSS - Hospital for Special Surgery                                                                                                                                                                                                                                                                                                                                                            | i am learning path, Physician Acute Care Hospital Model 2, Remedy University                                                                                                                                                                             |
      | Upload Remedy TCS, verify email, login with created user and validate tiles       | Super Admin | Remedy TCS      |     | RTCSFirstName        | RTCSLastName        | 546-546-5655 | Episodes, Episodes 2.0, Reports, Lessons      |                      | Mountainside Hospital        | Mountainside Hospital--BPCI Model 2                                      | Mountainside Hospital--2070-047--Mountainside Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | Episodes, Episodes 2.0, Reports, TCI, Lessons      | Administration, Physician Connect               | ROLE_TCS       | Patient ID     | Episode DRG Issues           |      | Mountainside Hospital                                                                                                                                                                                                                                                                                                                                                                         | Learning Pathway 2, max-test-052417, Clinical Operations Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University                                                                                                           |
      | Upload Remedy LPN, verify email, login with created user and validate tiles       | Super Admin | Remedy LPN      |     | RLPNFirstName        | RLPNLastName        | 989-898-9898 | Episodes, Episodes 2.0, Reports, Lessons      |                      | Nebraska Spine Center        | Nebraska Spine Center--BPCI Model 3, Nebraska Spine Center--BPCI Model 2 | Nebraska Spine Center--2070-a12--Alegent Creighton Health Bergan Mercy Medical Ctr, Nebraska Spine Center--2070-a12--Alegent Creighton Health Immanuel Medical Center, Nebraska Spine Center--2070-a12--Alegent Creighton Health Lakeside Hospital,Nebraska Spine Center--2070-a12--Alegent Creighton Health Midlands Hospital, Nebraska Spine Center--2070-a12--Alegent Health Mercy Hospital, Nebraska Spine Center--2070-a12--Bryan Medical Center, Nebraska Spine Center--2070-a12--Methodist Jennie Edmundson,Nebraska Spine Center--2070-a12--Nebraska Orthopaedic Hospital,Nebraska Spine Center--2070-a12--Nebraska Spine Hospital,Nebraska Spine Center--2070-a12--The Nebraska Medical Center,Nebraska Spine Center--2070-a12--The Nebraska Methodist Hospital,Nebraska Spine Center--3056-a58--Alegent Creighton Health Bergan Mercy Medical Ctr, Nebraska Spine Center--3056-a58--Alegent Creighton Health Immanuel Medical Center, Nebraska Spine Center--3056-a58--Alegent Creighton Health Lakeside Hospital,Nebraska Spine Center--3056-a58--Alegent Creighton Health Midlands Hospital,Nebraska Spine Center--3056-a58--Alegent Health Mercy Hospital,Nebraska Spine Center--3056-a58--Bryan Medical Center, Nebraska Spine Center--3056-a58--Methodist Jennie Edmundson, Nebraska Spine Center--3056-a58--Nebraska Orthopaedic Hospital,Nebraska Spine Center--3056-a58--Nebraska Spine Hospital, Nebraska Spine Center--3056-a58--The Nebraska Medical Center, Nebraska Spine Center--3056-a58--The Nebraska Methodist Hospital | Episodes, Episodes 2.0, Reports, TCI, Lessons      | Administration, Physician Connect               | ROLE_LPN       | Patient ID     | Episode DRG Issues           |      | Alegent Health Mercy Hospital,Methodist Jennie Edmundson,Bryan Medical Center,The Nebraska Medical Center,The Nebraska Methodist Hospital,Alegent Creighton Health Bergan Mercy Medical Ctr, Alegent Creighton Health Immanuel Medical Center, Alegent Creighton Health Midlands Hospital, Nebraska Orthopaedic Hospital, Alegent Creighton Health Lakeside Hospital, Nebraska Spine Hospital |                                                                                                                                                                                                                                                          |
      | Upload Remedy RN , verify email, login with created user and validate tiles       | Super Admin | Remedy RN       |     | RRNFirstName         | RRNLastName         | 987-890-9878 | Episodes, Episodes 2.0, Reports, Lessons      |                      | Penn                         | Penn--BPCI Model 2                                                       | Penn--2070-020--Upenn - Hospital Of The Univ. Of Pennsylvania, Penn--2070-021--Upenn - Penn Presbyterian Hospital,Penn--2070-022--Upenn - Pennsylvania Hospital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | Episodes, Episodes 2.0, Reports, TCI, Lessons      | Administration, Physician Connect               | ROLE_RN        | Patient ID     | Episode DRG Issues           |      | UPenn - Hospital of the Univ. of Pennsylvania, UPenn - Pennsylvania Hospital, UPenn - Penn Presbyterian Hospital                                                                                                                                                                                                                                                                              | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2, Remedy University |
      | Upload Remedy Field RN , verify email, login with created user and validate tiles | Super Admin | Remedy Field RN |     | RFRNFirstName        | RFRNLastName        |              | Episodes, Episodes 2.0, Reports, Lessons      |                      | Avon Health Center           | Avon Health Center--BPCI Model 3                                         | Avon Health Center--3056-r31--Avon Health                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | Episodes, Episodes 2.0, Reports, TCI, Lessons      | Administration, Physician Connect               | ROLE_FRN       | Patient ID     | Episode DRG Issues [Model 3] |      | Avon Health                                                                                                                                                                                                                                                                                                                                                                                   | i am learning path, Learning Pathway 2, max-test-052417, New learning Path, Care Coordination External, Clinical Operations Acute Care Hospital Model 2, Executive Acute Care Hospital Model 2, Physician Acute Care Hospital Model 2                    |
